package co.edu.upb.proyectoAula;

import java.util.HashMap;

import co.edu.upb.proyectoAula.data_structures.Grafo;
import co.edu.upb.proyectoAula.data_structures.Nodo;

public class GrafoMapa {
	 
    public static Grafo crear() {
        Grafo grafo = new Grafo();
        HashMap<String, Nodo> n = new HashMap<>();
 
        n.put("AA", new Nodo("AA", 30, 25));
        n.put("AB", new Nodo("AB", 85, 25));
        n.put("AC", new Nodo("AC", 140, 25));
        n.put("AE", new Nodo("AE", 250, 25));
        n.put("AG", new Nodo("AG", 360, 25));
        n.put("AH", new Nodo("AH", 415, 25));
        n.put("AI", new Nodo("AI", 470, 25));
        n.put("AK", new Nodo("AK", 580, 25));
        n.put("AL", new Nodo("AL", 635, 25));
        n.put("AM", new Nodo("AM", 690, 25));
        n.put("AP", new Nodo("AP", 855, 25));
        n.put("AQ", new Nodo("AQ", 910, 25));
        n.put("AR", new Nodo("AR", 965, 25));
        n.put("BA", new Nodo("BA", 30, 64));
        n.put("BB", new Nodo("BB", 85, 64));
        n.put("BD", new Nodo("BD", 195, 64));
        n.put("BE", new Nodo("BE", 250, 64));
        n.put("BG", new Nodo("BG", 360, 64));
        n.put("BH", new Nodo("BH", 415, 64));
        n.put("BJ", new Nodo("BJ", 525, 64));
        n.put("BK", new Nodo("BK", 580, 64));
        n.put("BL", new Nodo("BL", 635, 64));
        n.put("BM", new Nodo("BM", 690, 64));
        n.put("BN", new Nodo("BN", 745, 64));
        n.put("BO", new Nodo("BO", 800, 64));
        n.put("BP", new Nodo("BP", 855, 64));
        n.put("BQ", new Nodo("BQ", 910, 64));
        n.put("BR", new Nodo("BR", 965, 64));
        n.put("CA", new Nodo("CA", 30, 103));
        n.put("CC", new Nodo("CC", 140, 103));
        n.put("CD", new Nodo("CD", 195, 103));
        n.put("CE", new Nodo("CE", 250, 103));
        n.put("CF", new Nodo("CF", 305, 103));
        n.put("CG", new Nodo("CG", 360, 103));
        n.put("CI", new Nodo("CI", 470, 103));
        n.put("CK", new Nodo("CK", 580, 103));
        n.put("CL", new Nodo("CL", 635, 103));
        n.put("CN", new Nodo("CN", 745, 103));
        n.put("CO", new Nodo("CO", 800, 103));
        n.put("CP", new Nodo("CP", 855, 103));
        n.put("CQ", new Nodo("CQ", 910, 103));
        n.put("DA", new Nodo("DA", 30, 142));
        n.put("DB", new Nodo("DB", 85, 142));
        n.put("DD", new Nodo("DD", 195, 142));
        n.put("DF", new Nodo("DF", 305, 142));
        n.put("DG", new Nodo("DG", 360, 142));
        n.put("DI", new Nodo("DI", 470, 142));
        n.put("DJ", new Nodo("DJ", 525, 142));
        n.put("DK", new Nodo("DK", 580, 142));
        n.put("DL", new Nodo("DL", 635, 142));
        n.put("DN", new Nodo("DN", 745, 142));
        n.put("DO", new Nodo("DO", 800, 142));
        n.put("DP", new Nodo("DP", 855, 142));
        n.put("DQ", new Nodo("DQ", 910, 142));
        n.put("DR", new Nodo("DR", 965, 142));
        n.put("EA", new Nodo("EA", 30, 181));
        n.put("EB", new Nodo("EB", 85, 181));
        n.put("EC", new Nodo("EC", 140, 181));
        n.put("ED", new Nodo("ED", 195, 181));
        n.put("EE", new Nodo("EE", 250, 181));
        n.put("EF", new Nodo("EF", 305, 181));
        n.put("EH", new Nodo("EH", 415, 181));
        n.put("EI", new Nodo("EI", 470, 181));
        n.put("EJ", new Nodo("EJ", 525, 181));
        n.put("EK", new Nodo("EK", 580, 181));
        n.put("EM", new Nodo("EM", 690, 181));
        n.put("EN", new Nodo("EN", 745, 181));
        n.put("EO", new Nodo("EO", 800, 181));
        n.put("EQ", new Nodo("EQ", 910, 181));
        n.put("FA", new Nodo("FA", 30, 220));
        n.put("FB", new Nodo("FB", 85, 220));
        n.put("FD", new Nodo("FD", 195, 220));
        n.put("FE", new Nodo("FE", 250, 220));
        n.put("FG", new Nodo("FG", 360, 220));
        n.put("FH", new Nodo("FH", 415, 220));
        n.put("FI", new Nodo("FI", 470, 220));
        n.put("FK", new Nodo("FK", 580, 220));
        n.put("FL", new Nodo("FL", 635, 220));
        n.put("FM", new Nodo("FM", 690, 220));
        n.put("FP", new Nodo("FP", 855, 220));
        n.put("FR", new Nodo("FR", 965, 220));
        n.put("GA", new Nodo("GA", 30, 260));
        n.put("GC", new Nodo("GC", 140, 260));
        n.put("GD", new Nodo("GD", 195, 260));
        n.put("GE", new Nodo("GE", 250, 260));
        n.put("GF", new Nodo("GF", 305, 260));
        n.put("GH", new Nodo("GH", 415, 260));
        n.put("GI", new Nodo("GI", 470, 260));
        n.put("GJ", new Nodo("GJ", 525, 260));
        n.put("GL", new Nodo("GL", 635, 260));
        n.put("GN", new Nodo("GN", 745, 260));
        n.put("GO", new Nodo("GO", 800, 260));
        n.put("GP", new Nodo("GP", 855, 260));
        n.put("GR", new Nodo("GR", 965, 260));
        n.put("HA", new Nodo("HA", 30, 299));
        n.put("HB", new Nodo("HB", 85, 299));
        n.put("HD", new Nodo("HD", 195, 299));
        n.put("HE", new Nodo("HE", 250, 299));
        n.put("HG", new Nodo("HG", 360, 299));
        n.put("HH", new Nodo("HH", 415, 299));
        n.put("HI", new Nodo("HI", 470, 299));
        n.put("HJ", new Nodo("HJ", 525, 299));
        n.put("HK", new Nodo("HK", 580, 299));
        n.put("HL", new Nodo("HL", 635, 299));
        n.put("HM", new Nodo("HM", 690, 299));
        n.put("HN", new Nodo("HN", 745, 299));
        n.put("HP", new Nodo("HP", 855, 299));
        n.put("HQ", new Nodo("HQ", 910, 299));
        n.put("HR", new Nodo("HR", 965, 299));
        n.put("IA", new Nodo("IA", 30, 338));
        n.put("IB", new Nodo("IB", 85, 338));
        n.put("IC", new Nodo("IC", 140, 338));
        n.put("IE", new Nodo("IE", 250, 338));
        n.put("IF", new Nodo("IF", 305, 338));
        n.put("IG", new Nodo("IG", 360, 338));
        n.put("IH", new Nodo("IH", 415, 338));
        n.put("IJ", new Nodo("IJ", 525, 338));
        n.put("IK", new Nodo("IK", 580, 338));
        n.put("IL", new Nodo("IL", 635, 338));
        n.put("IN", new Nodo("IN", 745, 338));
        n.put("IO", new Nodo("IO", 800, 338));
        n.put("IQ", new Nodo("IQ", 910, 338));
        n.put("JB", new Nodo("JB", 85, 377));
        n.put("JC", new Nodo("JC", 140, 377));
        n.put("JD", new Nodo("JD", 195, 377));
        n.put("JE", new Nodo("JE", 250, 377));
        n.put("JF", new Nodo("JF", 305, 377));
        n.put("JG", new Nodo("JG", 360, 377));
        n.put("JH", new Nodo("JH", 415, 377));
        n.put("JI", new Nodo("JI", 470, 377));
        n.put("JJ", new Nodo("JJ", 525, 377));
        n.put("JK", new Nodo("JK", 580, 377));
        n.put("JM", new Nodo("JM", 690, 377));
        n.put("JO", new Nodo("JO", 800, 377));
        n.put("JP", new Nodo("JP", 855, 377));
        n.put("JQ", new Nodo("JQ", 910, 377));
        n.put("JR", new Nodo("JR", 965, 377));
        n.put("KA", new Nodo("KA", 30, 416));
        n.put("KB", new Nodo("KB", 85, 416));
        n.put("KD", new Nodo("KD", 195, 416));
        n.put("KG", new Nodo("KG", 360, 416));
        n.put("KI", new Nodo("KI", 470, 416));
        n.put("KK", new Nodo("KK", 580, 416));
        n.put("KL", new Nodo("KL", 635, 416));
        n.put("KM", new Nodo("KM", 690, 416));
        n.put("KN", new Nodo("KN", 745, 416));
        n.put("KO", new Nodo("KO", 800, 416));
        n.put("KQ", new Nodo("KQ", 910, 416));
        n.put("KR", new Nodo("KR", 965, 416));
        n.put("LB", new Nodo("LB", 85, 455));
        n.put("LD", new Nodo("LD", 195, 455));
        n.put("LE", new Nodo("LE", 250, 455));
        n.put("LF", new Nodo("LF", 305, 455));
        n.put("LG", new Nodo("LG", 360, 455));
        n.put("LI", new Nodo("LI", 470, 455));
        n.put("LJ", new Nodo("LJ", 525, 455));
        n.put("LK", new Nodo("LK", 580, 455));
        n.put("LN", new Nodo("LN", 745, 455));
        n.put("LO", new Nodo("LO", 800, 455));
        n.put("LP", new Nodo("LP", 855, 455));
        n.put("LR", new Nodo("LR", 965, 455));
        n.put("MA", new Nodo("MA", 30, 494));
        n.put("MC", new Nodo("MC", 140, 494));
        n.put("MD", new Nodo("MD", 195, 494));
        n.put("MF", new Nodo("MF", 305, 494));
        n.put("MH", new Nodo("MH", 415, 494));
        n.put("MI", new Nodo("MI", 470, 494));
        n.put("MJ", new Nodo("MJ", 525, 494));
        n.put("MK", new Nodo("MK", 580, 494));
        n.put("ML", new Nodo("ML", 635, 494));
        n.put("MM", new Nodo("MM", 690, 494));
        n.put("MN", new Nodo("MN", 745, 494));
        n.put("MP", new Nodo("MP", 855, 494));
        n.put("MQ", new Nodo("MQ", 910, 494));
        n.put("NB", new Nodo("NB", 85, 533));
        n.put("NC", new Nodo("NC", 140, 533));
        n.put("ND", new Nodo("ND", 195, 533));
        n.put("NE", new Nodo("NE", 250, 533));
        n.put("NF", new Nodo("NF", 305, 533));
        n.put("NG", new Nodo("NG", 360, 533));
        n.put("NH", new Nodo("NH", 415, 533));
        n.put("NI", new Nodo("NI", 470, 533));
        n.put("NK", new Nodo("NK", 580, 533));
        n.put("NL", new Nodo("NL", 635, 533));
        n.put("NN", new Nodo("NN", 745, 533));
        n.put("NO", new Nodo("NO", 800, 533));
        n.put("NQ", new Nodo("NQ", 910, 533));
        n.put("NR", new Nodo("NR", 965, 533));
        n.put("OA", new Nodo("OA", 30, 572));
        n.put("OB", new Nodo("OB", 85, 572));
        n.put("OC", new Nodo("OC", 140, 572));
        n.put("OD", new Nodo("OD", 195, 572));
        n.put("OE", new Nodo("OE", 250, 572));
        n.put("OG", new Nodo("OG", 360, 572));
        n.put("OI", new Nodo("OI", 470, 572));
        n.put("OJ", new Nodo("OJ", 525, 572));
        n.put("OL", new Nodo("OL", 635, 572));
        n.put("OM", new Nodo("OM", 690, 572));
        n.put("OO", new Nodo("OO", 800, 572));
        n.put("OP", new Nodo("OP", 855, 572));
        n.put("OQ", new Nodo("OQ", 910, 572));
        n.put("OR", new Nodo("OR", 965, 572));
        n.put("PA", new Nodo("PA", 30, 611));
        n.put("PC", new Nodo("PC", 140, 611));
        n.put("PE", new Nodo("PE", 250, 611));
        n.put("PF", new Nodo("PF", 305, 611));
        n.put("PG", new Nodo("PG", 360, 611));
        n.put("PH", new Nodo("PH", 415, 611));
        n.put("PJ", new Nodo("PJ", 525, 611));
        n.put("PK", new Nodo("PK", 580, 611));
        n.put("PM", new Nodo("PM", 690, 611));
        n.put("PN", new Nodo("PN", 745, 611));
        n.put("PP", new Nodo("PP", 855, 611));
        n.put("PQ", new Nodo("PQ", 910, 611));
        n.put("PR", new Nodo("PR", 965, 611));
        n.put("QB", new Nodo("QB", 85, 651));
        n.put("QC", new Nodo("QC", 140, 651));
        n.put("QD", new Nodo("QD", 195, 651));
        n.put("QF", new Nodo("QF", 305, 651));
        n.put("QG", new Nodo("QG", 360, 651));
        n.put("QH", new Nodo("QH", 415, 651));
        n.put("QI", new Nodo("QI", 470, 651));
        n.put("QJ", new Nodo("QJ", 525, 651));
        n.put("QK", new Nodo("QK", 580, 651));
        n.put("QL", new Nodo("QL", 635, 651));
        n.put("QM", new Nodo("QM", 690, 651));
        n.put("QN", new Nodo("QN", 745, 651));
        n.put("QO", new Nodo("QO", 800, 651));
        n.put("QP", new Nodo("QP", 855, 651));
        n.put("QQ", new Nodo("QQ", 910, 651));
        n.put("RA", new Nodo("RA", 30, 690));
        n.put("RB", new Nodo("RB", 85, 690));
        n.put("RE", new Nodo("RE", 250, 690));
        n.put("RF", new Nodo("RF", 305, 690));
        n.put("RG", new Nodo("RG", 360, 690));
        n.put("RH", new Nodo("RH", 415, 690));
        n.put("RI", new Nodo("RI", 470, 690));
        n.put("RJ", new Nodo("RJ", 525, 690));
        n.put("RL", new Nodo("RL", 635, 690));
        n.put("RM", new Nodo("RM", 690, 690));
        n.put("RN", new Nodo("RN", 745, 690));
        n.put("RP", new Nodo("RP", 855, 690));
        n.put("RQ", new Nodo("RQ", 910, 690));
        n.put("RR", new Nodo("RR", 965, 690));
 
        for (Nodo nodo : n.values()) grafo.agregarNodo(nodo);
 
 
        // Derecha 15 - Abajo 10 - Izquierda 15 - Arriba 30 - Diagonal 33
        grafo.agregarArista(n.get("AA"), n.get("AB"), 15);
        grafo.agregarArista(n.get("AB"), n.get("AA"), 15);
        grafo.agregarArista(n.get("AA"), n.get("BA"), 10);
        grafo.agregarArista(n.get("BA"), n.get("AA"), 30);
        grafo.agregarArista(n.get("AA"), n.get("BB"), 33);
        grafo.agregarArista(n.get("BB"), n.get("AA"), 33);
        grafo.agregarArista(n.get("AB"), n.get("AC"), 15);
        grafo.agregarArista(n.get("AC"), n.get("AB"), 15);
        grafo.agregarArista(n.get("AB"), n.get("BB"), 10);
        grafo.agregarArista(n.get("BB"), n.get("AB"), 30);
        grafo.agregarArista(n.get("AB"), n.get("BA"), 33);
        grafo.agregarArista(n.get("BA"), n.get("AB"), 33);
        grafo.agregarArista(n.get("AC"), n.get("BD"), 33);
        grafo.agregarArista(n.get("BD"), n.get("AC"), 33);
        grafo.agregarArista(n.get("AC"), n.get("BB"), 33);
        grafo.agregarArista(n.get("BB"), n.get("AC"), 33);
        grafo.agregarArista(n.get("AE"), n.get("BE"), 10);
        grafo.agregarArista(n.get("BE"), n.get("AE"), 30);
        grafo.agregarArista(n.get("AE"), n.get("BD"), 33);
        grafo.agregarArista(n.get("BD"), n.get("AE"), 33);
        grafo.agregarArista(n.get("AG"), n.get("AH"), 15);
        grafo.agregarArista(n.get("AH"), n.get("AG"), 15);
        grafo.agregarArista(n.get("AG"), n.get("BG"), 10);
        grafo.agregarArista(n.get("BG"), n.get("AG"), 30);
        grafo.agregarArista(n.get("AG"), n.get("BH"), 33);
        grafo.agregarArista(n.get("BH"), n.get("AG"), 33);
        grafo.agregarArista(n.get("AH"), n.get("AI"), 15);
        grafo.agregarArista(n.get("AI"), n.get("AH"), 15);
        grafo.agregarArista(n.get("AH"), n.get("BH"), 10);
        grafo.agregarArista(n.get("BH"), n.get("AH"), 30);
        grafo.agregarArista(n.get("AH"), n.get("BG"), 33);
        grafo.agregarArista(n.get("BG"), n.get("AH"), 33);
        grafo.agregarArista(n.get("AI"), n.get("BJ"), 33);
        grafo.agregarArista(n.get("BJ"), n.get("AI"), 33);
        grafo.agregarArista(n.get("AI"), n.get("BH"), 33);
        grafo.agregarArista(n.get("BH"), n.get("AI"), 33);
        grafo.agregarArista(n.get("AK"), n.get("AL"), 15);
        grafo.agregarArista(n.get("AL"), n.get("AK"), 15);
        grafo.agregarArista(n.get("AK"), n.get("BK"), 10);
        grafo.agregarArista(n.get("BK"), n.get("AK"), 30);
        grafo.agregarArista(n.get("AK"), n.get("BL"), 33);
        grafo.agregarArista(n.get("BL"), n.get("AK"), 33);
        grafo.agregarArista(n.get("AK"), n.get("BJ"), 33);
        grafo.agregarArista(n.get("BJ"), n.get("AK"), 33);
        grafo.agregarArista(n.get("AL"), n.get("AM"), 15);
        grafo.agregarArista(n.get("AM"), n.get("AL"), 15);
        grafo.agregarArista(n.get("AL"), n.get("BL"), 10);
        grafo.agregarArista(n.get("BL"), n.get("AL"), 30);
        grafo.agregarArista(n.get("AL"), n.get("BM"), 33);
        grafo.agregarArista(n.get("BM"), n.get("AL"), 33);
        grafo.agregarArista(n.get("AL"), n.get("BK"), 33);
        grafo.agregarArista(n.get("BK"), n.get("AL"), 33);
        grafo.agregarArista(n.get("AM"), n.get("BM"), 10);
        grafo.agregarArista(n.get("BM"), n.get("AM"), 30);
        grafo.agregarArista(n.get("AM"), n.get("BN"), 33);
        grafo.agregarArista(n.get("BN"), n.get("AM"), 33);
        grafo.agregarArista(n.get("AM"), n.get("BL"), 33);
        grafo.agregarArista(n.get("BL"), n.get("AM"), 33);
        grafo.agregarArista(n.get("AP"), n.get("AQ"), 15);
        grafo.agregarArista(n.get("AQ"), n.get("AP"), 15);
        grafo.agregarArista(n.get("AP"), n.get("BP"), 10);
        grafo.agregarArista(n.get("BP"), n.get("AP"), 30);
        grafo.agregarArista(n.get("AP"), n.get("BQ"), 33);
        grafo.agregarArista(n.get("BQ"), n.get("AP"), 33);
        grafo.agregarArista(n.get("AP"), n.get("BO"), 33);
        grafo.agregarArista(n.get("BO"), n.get("AP"), 33);
        grafo.agregarArista(n.get("AQ"), n.get("AR"), 15);
        grafo.agregarArista(n.get("AR"), n.get("AQ"), 15);
        grafo.agregarArista(n.get("AQ"), n.get("BQ"), 10);
        grafo.agregarArista(n.get("BQ"), n.get("AQ"), 30);
        grafo.agregarArista(n.get("AQ"), n.get("BR"), 33);
        grafo.agregarArista(n.get("BR"), n.get("AQ"), 33);
        grafo.agregarArista(n.get("AQ"), n.get("BP"), 33);
        grafo.agregarArista(n.get("BP"), n.get("AQ"), 33);
        grafo.agregarArista(n.get("AR"), n.get("BR"), 10);
        grafo.agregarArista(n.get("BR"), n.get("AR"), 30);
        grafo.agregarArista(n.get("AR"), n.get("BQ"), 33);
        grafo.agregarArista(n.get("BQ"), n.get("AR"), 33);
        grafo.agregarArista(n.get("BA"), n.get("BB"), 15);
        grafo.agregarArista(n.get("BB"), n.get("BA"), 15);
        grafo.agregarArista(n.get("BA"), n.get("CA"), 10);
        grafo.agregarArista(n.get("CA"), n.get("BA"), 30);
        grafo.agregarArista(n.get("BB"), n.get("CC"), 33);
        grafo.agregarArista(n.get("CC"), n.get("BB"), 33);
        grafo.agregarArista(n.get("BB"), n.get("CA"), 33);
        grafo.agregarArista(n.get("CA"), n.get("BB"), 33);
        grafo.agregarArista(n.get("BD"), n.get("BE"), 15);
        grafo.agregarArista(n.get("BE"), n.get("BD"), 15);
        grafo.agregarArista(n.get("BD"), n.get("CD"), 10);
        grafo.agregarArista(n.get("CD"), n.get("BD"), 30);
        grafo.agregarArista(n.get("BD"), n.get("CC"), 33);
        grafo.agregarArista(n.get("CC"), n.get("BD"), 33);
        grafo.agregarArista(n.get("BE"), n.get("CF"), 33);
        grafo.agregarArista(n.get("CF"), n.get("BE"), 33);
        grafo.agregarArista(n.get("BE"), n.get("CD"), 33);
        grafo.agregarArista(n.get("CD"), n.get("BE"), 33);
        grafo.agregarArista(n.get("BG"), n.get("BH"), 15);
        grafo.agregarArista(n.get("BH"), n.get("BG"), 15);
        grafo.agregarArista(n.get("BG"), n.get("CG"), 10);
        grafo.agregarArista(n.get("CG"), n.get("BG"), 30);
        grafo.agregarArista(n.get("BG"), n.get("CF"), 33);
        grafo.agregarArista(n.get("CF"), n.get("BG"), 33);
        grafo.agregarArista(n.get("BH"), n.get("CI"), 33);
        grafo.agregarArista(n.get("CI"), n.get("BH"), 33);
        grafo.agregarArista(n.get("BH"), n.get("CG"), 33);
        grafo.agregarArista(n.get("CG"), n.get("BH"), 33);
        grafo.agregarArista(n.get("BJ"), n.get("BK"), 15);
        grafo.agregarArista(n.get("BK"), n.get("BJ"), 15);
        grafo.agregarArista(n.get("BJ"), n.get("CK"), 33);
        grafo.agregarArista(n.get("CK"), n.get("BJ"), 33);
        grafo.agregarArista(n.get("BJ"), n.get("CI"), 33);
        grafo.agregarArista(n.get("CI"), n.get("BJ"), 33);
        grafo.agregarArista(n.get("BK"), n.get("BL"), 15);
        grafo.agregarArista(n.get("BL"), n.get("BK"), 15);
        grafo.agregarArista(n.get("BK"), n.get("CK"), 10);
        grafo.agregarArista(n.get("CK"), n.get("BK"), 30);
        grafo.agregarArista(n.get("BK"), n.get("CL"), 33);
        grafo.agregarArista(n.get("CL"), n.get("BK"), 33);
        grafo.agregarArista(n.get("BL"), n.get("BM"), 15);
        grafo.agregarArista(n.get("BM"), n.get("BL"), 15);
        grafo.agregarArista(n.get("BL"), n.get("CL"), 10);
        grafo.agregarArista(n.get("CL"), n.get("BL"), 30);
        grafo.agregarArista(n.get("BL"), n.get("CK"), 33);
        grafo.agregarArista(n.get("CK"), n.get("BL"), 33);
        grafo.agregarArista(n.get("BM"), n.get("BN"), 15);
        grafo.agregarArista(n.get("BN"), n.get("BM"), 15);
        grafo.agregarArista(n.get("BM"), n.get("CN"), 33);
        grafo.agregarArista(n.get("CN"), n.get("BM"), 33);
        grafo.agregarArista(n.get("BM"), n.get("CL"), 33);
        grafo.agregarArista(n.get("CL"), n.get("BM"), 33);
        grafo.agregarArista(n.get("BN"), n.get("BO"), 15);
        grafo.agregarArista(n.get("BO"), n.get("BN"), 15);
        grafo.agregarArista(n.get("BN"), n.get("CN"), 10);
        grafo.agregarArista(n.get("CN"), n.get("BN"), 30);
        grafo.agregarArista(n.get("BN"), n.get("CO"), 33);
        grafo.agregarArista(n.get("CO"), n.get("BN"), 33);
        grafo.agregarArista(n.get("BO"), n.get("BP"), 15);
        grafo.agregarArista(n.get("BP"), n.get("BO"), 15);
        grafo.agregarArista(n.get("BO"), n.get("CO"), 10);
        grafo.agregarArista(n.get("CO"), n.get("BO"), 30);
        grafo.agregarArista(n.get("BO"), n.get("CP"), 33);
        grafo.agregarArista(n.get("CP"), n.get("BO"), 33);
        grafo.agregarArista(n.get("BO"), n.get("CN"), 33);
        grafo.agregarArista(n.get("CN"), n.get("BO"), 33);
        grafo.agregarArista(n.get("BP"), n.get("BQ"), 15);
        grafo.agregarArista(n.get("BQ"), n.get("BP"), 15);
        grafo.agregarArista(n.get("BP"), n.get("CP"), 10);
        grafo.agregarArista(n.get("CP"), n.get("BP"), 30);
        grafo.agregarArista(n.get("BP"), n.get("CQ"), 33);
        grafo.agregarArista(n.get("CQ"), n.get("BP"), 33);
        grafo.agregarArista(n.get("BP"), n.get("CO"), 33);
        grafo.agregarArista(n.get("CO"), n.get("BP"), 33);
        grafo.agregarArista(n.get("BQ"), n.get("BR"), 15);
        grafo.agregarArista(n.get("BR"), n.get("BQ"), 15);
        grafo.agregarArista(n.get("BQ"), n.get("CQ"), 10);
        grafo.agregarArista(n.get("CQ"), n.get("BQ"), 30);
        grafo.agregarArista(n.get("BQ"), n.get("CP"), 33);
        grafo.agregarArista(n.get("CP"), n.get("BQ"), 33);
        grafo.agregarArista(n.get("BR"), n.get("CQ"), 33);
        grafo.agregarArista(n.get("CQ"), n.get("BR"), 33);
        grafo.agregarArista(n.get("CA"), n.get("DA"), 10);
        grafo.agregarArista(n.get("DA"), n.get("CA"), 30);
        grafo.agregarArista(n.get("CA"), n.get("DB"), 33);
        grafo.agregarArista(n.get("DB"), n.get("CA"), 33);
        grafo.agregarArista(n.get("CC"), n.get("CD"), 15);
        grafo.agregarArista(n.get("CD"), n.get("CC"), 15);
        grafo.agregarArista(n.get("CC"), n.get("DD"), 33);
        grafo.agregarArista(n.get("DD"), n.get("CC"), 33);
        grafo.agregarArista(n.get("CC"), n.get("DB"), 33);
        grafo.agregarArista(n.get("DB"), n.get("CC"), 33);
        grafo.agregarArista(n.get("CD"), n.get("DD"), 10);
        grafo.agregarArista(n.get("DD"), n.get("CD"), 30);
        grafo.agregarArista(n.get("CD"), n.get("CE"), 15);
        grafo.agregarArista(n.get("CE"), n.get("CD"), 15);
        grafo.agregarArista(n.get("CE"), n.get("BE"), 30);
        grafo.agregarArista(n.get("CE"), n.get("CF"), 15);
        grafo.agregarArista(n.get("CF"), n.get("CE"), 15);
        grafo.agregarArista(n.get("CE"), n.get("DD"), 33);
        grafo.agregarArista(n.get("DD"), n.get("CE"), 33);
        grafo.agregarArista(n.get("CE"), n.get("DF"), 33);
        grafo.agregarArista(n.get("DF"), n.get("CE"), 33);
        grafo.agregarArista(n.get("CF"), n.get("CG"), 15);
        grafo.agregarArista(n.get("CG"), n.get("CF"), 15);
        grafo.agregarArista(n.get("CF"), n.get("DF"), 10);
        grafo.agregarArista(n.get("DF"), n.get("CF"), 30);
        grafo.agregarArista(n.get("CF"), n.get("DG"), 33);
        grafo.agregarArista(n.get("DG"), n.get("CF"), 33);
        grafo.agregarArista(n.get("CG"), n.get("DG"), 10);
        grafo.agregarArista(n.get("DG"), n.get("CG"), 30);
        grafo.agregarArista(n.get("CG"), n.get("DF"), 33);
        grafo.agregarArista(n.get("DF"), n.get("CG"), 33);
        grafo.agregarArista(n.get("CI"), n.get("DI"), 10);
        grafo.agregarArista(n.get("DI"), n.get("CI"), 30);
        grafo.agregarArista(n.get("CI"), n.get("DJ"), 33);
        grafo.agregarArista(n.get("DJ"), n.get("CI"), 33);
        grafo.agregarArista(n.get("CK"), n.get("CL"), 15);
        grafo.agregarArista(n.get("CL"), n.get("CK"), 15);
        grafo.agregarArista(n.get("CK"), n.get("DK"), 10);
        grafo.agregarArista(n.get("DK"), n.get("CK"), 30);
        grafo.agregarArista(n.get("CK"), n.get("DL"), 33);
        grafo.agregarArista(n.get("DL"), n.get("CK"), 33);
        grafo.agregarArista(n.get("CK"), n.get("DJ"), 33);
        grafo.agregarArista(n.get("DJ"), n.get("CK"), 33);
        grafo.agregarArista(n.get("CL"), n.get("DL"), 10);
        grafo.agregarArista(n.get("DL"), n.get("CL"), 30);
        grafo.agregarArista(n.get("CL"), n.get("DK"), 33);
        grafo.agregarArista(n.get("DK"), n.get("CL"), 33);
        grafo.agregarArista(n.get("CN"), n.get("CO"), 15);
        grafo.agregarArista(n.get("CO"), n.get("CN"), 15);
        grafo.agregarArista(n.get("CN"), n.get("DN"), 10);
        grafo.agregarArista(n.get("DN"), n.get("CN"), 30);
        grafo.agregarArista(n.get("CN"), n.get("DO"), 33);
        grafo.agregarArista(n.get("DO"), n.get("CN"), 33);
        grafo.agregarArista(n.get("CO"), n.get("CP"), 15);
        grafo.agregarArista(n.get("CP"), n.get("CO"), 15);
        grafo.agregarArista(n.get("CO"), n.get("DO"), 10);
        grafo.agregarArista(n.get("DO"), n.get("CO"), 30);
        grafo.agregarArista(n.get("CO"), n.get("DP"), 33);
        grafo.agregarArista(n.get("DP"), n.get("CO"), 33);
        grafo.agregarArista(n.get("CO"), n.get("DN"), 33);
        grafo.agregarArista(n.get("DN"), n.get("CO"), 33);
        grafo.agregarArista(n.get("CP"), n.get("CQ"), 15);
        grafo.agregarArista(n.get("CQ"), n.get("CP"), 15);
        grafo.agregarArista(n.get("CP"), n.get("DP"), 10);
        grafo.agregarArista(n.get("DP"), n.get("CP"), 30);
        grafo.agregarArista(n.get("CP"), n.get("DQ"), 33);
        grafo.agregarArista(n.get("DQ"), n.get("CP"), 33);
        grafo.agregarArista(n.get("CP"), n.get("DO"), 33);
        grafo.agregarArista(n.get("DO"), n.get("CP"), 33);
        grafo.agregarArista(n.get("CQ"), n.get("DQ"), 10);
        grafo.agregarArista(n.get("DQ"), n.get("CQ"), 30);
        grafo.agregarArista(n.get("CQ"), n.get("DR"), 33);
        grafo.agregarArista(n.get("DR"), n.get("CQ"), 33);
        grafo.agregarArista(n.get("CQ"), n.get("DP"), 33);
        grafo.agregarArista(n.get("DP"), n.get("CQ"), 33);
        grafo.agregarArista(n.get("DA"), n.get("DB"), 15);
        grafo.agregarArista(n.get("DB"), n.get("DA"), 15);
        grafo.agregarArista(n.get("DA"), n.get("EA"), 10);
        grafo.agregarArista(n.get("EA"), n.get("DA"), 30);
        grafo.agregarArista(n.get("DA"), n.get("EB"), 33);
        grafo.agregarArista(n.get("EB"), n.get("DA"), 33);
        grafo.agregarArista(n.get("DB"), n.get("EB"), 10);
        grafo.agregarArista(n.get("EB"), n.get("DB"), 30);
        grafo.agregarArista(n.get("DB"), n.get("EC"), 33);
        grafo.agregarArista(n.get("EC"), n.get("DB"), 33);
        grafo.agregarArista(n.get("DB"), n.get("EA"), 33);
        grafo.agregarArista(n.get("EA"), n.get("DB"), 33);
        grafo.agregarArista(n.get("DD"), n.get("ED"), 10);
        grafo.agregarArista(n.get("ED"), n.get("DD"), 30);
        grafo.agregarArista(n.get("DD"), n.get("EE"), 33);
        grafo.agregarArista(n.get("EE"), n.get("DD"), 33);
        grafo.agregarArista(n.get("DD"), n.get("EC"), 33);
        grafo.agregarArista(n.get("EC"), n.get("DD"), 33);
        grafo.agregarArista(n.get("DF"), n.get("DG"), 15);
        grafo.agregarArista(n.get("DG"), n.get("DF"), 15);
        grafo.agregarArista(n.get("DF"), n.get("EF"), 10);
        grafo.agregarArista(n.get("EF"), n.get("DF"), 30);
        grafo.agregarArista(n.get("DF"), n.get("EE"), 33);
        grafo.agregarArista(n.get("EE"), n.get("DF"), 33);
        grafo.agregarArista(n.get("DG"), n.get("EH"), 33);
        grafo.agregarArista(n.get("EH"), n.get("DG"), 33);
        grafo.agregarArista(n.get("DG"), n.get("EF"), 33);
        grafo.agregarArista(n.get("EF"), n.get("DG"), 33);
        grafo.agregarArista(n.get("DI"), n.get("DJ"), 15);
        grafo.agregarArista(n.get("DJ"), n.get("DI"), 15);
        grafo.agregarArista(n.get("DI"), n.get("EI"), 10);
        grafo.agregarArista(n.get("EI"), n.get("DI"), 30);
        grafo.agregarArista(n.get("DI"), n.get("EJ"), 33);
        grafo.agregarArista(n.get("EJ"), n.get("DI"), 33);
        grafo.agregarArista(n.get("DI"), n.get("EH"), 33);
        grafo.agregarArista(n.get("EH"), n.get("DI"), 33);
        grafo.agregarArista(n.get("DJ"), n.get("DK"), 15);
        grafo.agregarArista(n.get("DK"), n.get("DJ"), 15);
        grafo.agregarArista(n.get("DJ"), n.get("EJ"), 10);
        grafo.agregarArista(n.get("EJ"), n.get("DJ"), 30);
        grafo.agregarArista(n.get("DJ"), n.get("EK"), 33);
        grafo.agregarArista(n.get("EK"), n.get("DJ"), 33);
        grafo.agregarArista(n.get("DJ"), n.get("EI"), 33);
        grafo.agregarArista(n.get("EI"), n.get("DJ"), 33);
        grafo.agregarArista(n.get("DK"), n.get("DL"), 15);
        grafo.agregarArista(n.get("DL"), n.get("DK"), 15);
        grafo.agregarArista(n.get("DK"), n.get("EK"), 10);
        grafo.agregarArista(n.get("EK"), n.get("DK"), 30);
        grafo.agregarArista(n.get("DK"), n.get("EJ"), 33);
        grafo.agregarArista(n.get("EJ"), n.get("DK"), 33);
        grafo.agregarArista(n.get("DL"), n.get("EM"), 33);
        grafo.agregarArista(n.get("EM"), n.get("DL"), 33);
        grafo.agregarArista(n.get("DL"), n.get("EK"), 33);
        grafo.agregarArista(n.get("EK"), n.get("DL"), 33);
        grafo.agregarArista(n.get("DN"), n.get("DO"), 15);
        grafo.agregarArista(n.get("DO"), n.get("DN"), 15);
        grafo.agregarArista(n.get("DN"), n.get("EN"), 10);
        grafo.agregarArista(n.get("EN"), n.get("DN"), 30);
        grafo.agregarArista(n.get("DN"), n.get("EO"), 33);
        grafo.agregarArista(n.get("EO"), n.get("DN"), 33);
        grafo.agregarArista(n.get("DN"), n.get("EM"), 33);
        grafo.agregarArista(n.get("EM"), n.get("DN"), 33);
        grafo.agregarArista(n.get("DO"), n.get("DP"), 15);
        grafo.agregarArista(n.get("DP"), n.get("DO"), 15);
        grafo.agregarArista(n.get("DO"), n.get("EO"), 10);
        grafo.agregarArista(n.get("EO"), n.get("DO"), 30);
        grafo.agregarArista(n.get("DO"), n.get("EN"), 33);
        grafo.agregarArista(n.get("EN"), n.get("DO"), 33);
        grafo.agregarArista(n.get("DP"), n.get("DQ"), 15);
        grafo.agregarArista(n.get("DQ"), n.get("DP"), 15);
        grafo.agregarArista(n.get("DP"), n.get("EO"), 33);
        grafo.agregarArista(n.get("EO"), n.get("DP"), 33);
        grafo.agregarArista(n.get("DQ"), n.get("DR"), 15);
        grafo.agregarArista(n.get("DR"), n.get("DQ"), 15);
        grafo.agregarArista(n.get("DQ"), n.get("EQ"), 10);
        grafo.agregarArista(n.get("EQ"), n.get("DQ"), 30);
        grafo.agregarArista(n.get("EA"), n.get("EB"), 15);
        grafo.agregarArista(n.get("EB"), n.get("EA"), 15);
        grafo.agregarArista(n.get("EA"), n.get("FA"), 10);
        grafo.agregarArista(n.get("FA"), n.get("EA"), 30);
        grafo.agregarArista(n.get("EA"), n.get("FB"), 33);
        grafo.agregarArista(n.get("FB"), n.get("EA"), 33);
        grafo.agregarArista(n.get("EB"), n.get("EC"), 15);
        grafo.agregarArista(n.get("EC"), n.get("EB"), 15);
        grafo.agregarArista(n.get("EB"), n.get("FB"), 10);
        grafo.agregarArista(n.get("FB"), n.get("EB"), 30);
        grafo.agregarArista(n.get("EB"), n.get("FA"), 33);
        grafo.agregarArista(n.get("FA"), n.get("EB"), 33);
        grafo.agregarArista(n.get("EC"), n.get("ED"), 15);
        grafo.agregarArista(n.get("ED"), n.get("EC"), 15);
        grafo.agregarArista(n.get("EC"), n.get("FD"), 33);
        grafo.agregarArista(n.get("FD"), n.get("EC"), 33);
        grafo.agregarArista(n.get("EC"), n.get("FB"), 33);
        grafo.agregarArista(n.get("FB"), n.get("EC"), 33);
        grafo.agregarArista(n.get("ED"), n.get("EE"), 15);
        grafo.agregarArista(n.get("EE"), n.get("ED"), 15);
        grafo.agregarArista(n.get("ED"), n.get("FD"), 10);
        grafo.agregarArista(n.get("FD"), n.get("ED"), 30);
        grafo.agregarArista(n.get("ED"), n.get("FE"), 33);
        grafo.agregarArista(n.get("FE"), n.get("ED"), 33);
        grafo.agregarArista(n.get("EE"), n.get("EF"), 15);
        grafo.agregarArista(n.get("EF"), n.get("EE"), 15);
        grafo.agregarArista(n.get("EE"), n.get("FE"), 10);
        grafo.agregarArista(n.get("FE"), n.get("EE"), 30);
        grafo.agregarArista(n.get("EE"), n.get("FD"), 33);
        grafo.agregarArista(n.get("FD"), n.get("EE"), 33);
        grafo.agregarArista(n.get("EF"), n.get("FG"), 33);
        grafo.agregarArista(n.get("FG"), n.get("EF"), 33);
        grafo.agregarArista(n.get("EF"), n.get("FE"), 33);
        grafo.agregarArista(n.get("FE"), n.get("EF"), 33);
        grafo.agregarArista(n.get("EH"), n.get("EI"), 15);
        grafo.agregarArista(n.get("EI"), n.get("EH"), 15);
        grafo.agregarArista(n.get("EH"), n.get("FH"), 10);
        grafo.agregarArista(n.get("FH"), n.get("EH"), 30);
        grafo.agregarArista(n.get("EH"), n.get("FI"), 33);
        grafo.agregarArista(n.get("FI"), n.get("EH"), 33);
        grafo.agregarArista(n.get("EH"), n.get("FG"), 33);
        grafo.agregarArista(n.get("FG"), n.get("EH"), 33);
        grafo.agregarArista(n.get("EI"), n.get("EJ"), 15);
        grafo.agregarArista(n.get("EJ"), n.get("EI"), 15);
        grafo.agregarArista(n.get("EI"), n.get("FI"), 10);
        grafo.agregarArista(n.get("FI"), n.get("EI"), 30);
        grafo.agregarArista(n.get("EI"), n.get("FH"), 33);
        grafo.agregarArista(n.get("FH"), n.get("EI"), 33);
        grafo.agregarArista(n.get("EJ"), n.get("EK"), 15);
        grafo.agregarArista(n.get("EK"), n.get("EJ"), 15);
        grafo.agregarArista(n.get("EJ"), n.get("FK"), 33);
        grafo.agregarArista(n.get("FK"), n.get("EJ"), 33);
        grafo.agregarArista(n.get("EJ"), n.get("FI"), 33);
        grafo.agregarArista(n.get("FI"), n.get("EJ"), 33);
        grafo.agregarArista(n.get("EK"), n.get("FK"), 10);
        grafo.agregarArista(n.get("FK"), n.get("EK"), 30);
        grafo.agregarArista(n.get("EK"), n.get("FL"), 33);
        grafo.agregarArista(n.get("FL"), n.get("EK"), 33);
        grafo.agregarArista(n.get("EM"), n.get("EN"), 15);
        grafo.agregarArista(n.get("EN"), n.get("EM"), 15);
        grafo.agregarArista(n.get("EM"), n.get("FM"), 10);
        grafo.agregarArista(n.get("FM"), n.get("EM"), 30);
        grafo.agregarArista(n.get("EM"), n.get("FL"), 33);
        grafo.agregarArista(n.get("FL"), n.get("EM"), 33);
        grafo.agregarArista(n.get("EN"), n.get("EO"), 15);
        grafo.agregarArista(n.get("EO"), n.get("EN"), 15);
        grafo.agregarArista(n.get("EN"), n.get("FM"), 33);
        grafo.agregarArista(n.get("FM"), n.get("EN"), 33);
        grafo.agregarArista(n.get("EO"), n.get("FP"), 33);
        grafo.agregarArista(n.get("FP"), n.get("EO"), 33);
        grafo.agregarArista(n.get("EQ"), n.get("FP"), 33);
        grafo.agregarArista(n.get("FP"), n.get("EQ"), 33);
        grafo.agregarArista(n.get("EQ"), n.get("FR"), 33);
        grafo.agregarArista(n.get("FR"), n.get("EQ"), 33);
        grafo.agregarArista(n.get("EQ"), n.get("DP"), 33);
        grafo.agregarArista(n.get("DP"), n.get("EQ"), 33);
        grafo.agregarArista(n.get("EQ"), n.get("DR"), 33);
        grafo.agregarArista(n.get("DR"), n.get("EQ"), 33);
        grafo.agregarArista(n.get("FA"), n.get("FB"), 15);
        grafo.agregarArista(n.get("FB"), n.get("FA"), 15);
        grafo.agregarArista(n.get("FA"), n.get("GA"), 10);
        grafo.agregarArista(n.get("GA"), n.get("FA"), 30);
        grafo.agregarArista(n.get("FB"), n.get("GC"), 33);
        grafo.agregarArista(n.get("GC"), n.get("FB"), 33);
        grafo.agregarArista(n.get("FB"), n.get("GA"), 33);
        grafo.agregarArista(n.get("GA"), n.get("FB"), 33);
        grafo.agregarArista(n.get("FD"), n.get("FE"), 15);
        grafo.agregarArista(n.get("FE"), n.get("FD"), 15);
        grafo.agregarArista(n.get("FD"), n.get("GD"), 10);
        grafo.agregarArista(n.get("GD"), n.get("FD"), 30);
        grafo.agregarArista(n.get("FD"), n.get("GE"), 33);
        grafo.agregarArista(n.get("GE"), n.get("FD"), 33);
        grafo.agregarArista(n.get("FD"), n.get("GC"), 33);
        grafo.agregarArista(n.get("GC"), n.get("FD"), 33);
        grafo.agregarArista(n.get("FE"), n.get("GE"), 10);
        grafo.agregarArista(n.get("GE"), n.get("FE"), 30);
        grafo.agregarArista(n.get("FE"), n.get("GF"), 33);
        grafo.agregarArista(n.get("GF"), n.get("FE"), 33);
        grafo.agregarArista(n.get("FE"), n.get("GD"), 33);
        grafo.agregarArista(n.get("GD"), n.get("FE"), 33);
        grafo.agregarArista(n.get("FG"), n.get("FH"), 15);
        grafo.agregarArista(n.get("FH"), n.get("FG"), 15);
        grafo.agregarArista(n.get("FG"), n.get("GH"), 33);
        grafo.agregarArista(n.get("GH"), n.get("FG"), 33);
        grafo.agregarArista(n.get("FG"), n.get("GF"), 33);
        grafo.agregarArista(n.get("GF"), n.get("FG"), 33);
        grafo.agregarArista(n.get("FH"), n.get("FI"), 15);
        grafo.agregarArista(n.get("FI"), n.get("FH"), 15);
        grafo.agregarArista(n.get("FH"), n.get("GH"), 10);
        grafo.agregarArista(n.get("GH"), n.get("FH"), 30);
        grafo.agregarArista(n.get("FH"), n.get("GI"), 33);
        grafo.agregarArista(n.get("GI"), n.get("FH"), 33);
        grafo.agregarArista(n.get("FI"), n.get("GI"), 10);
        grafo.agregarArista(n.get("GI"), n.get("FI"), 30);
        grafo.agregarArista(n.get("FI"), n.get("GJ"), 33);
        grafo.agregarArista(n.get("GJ"), n.get("FI"), 33);
        grafo.agregarArista(n.get("FI"), n.get("GH"), 33);
        grafo.agregarArista(n.get("GH"), n.get("FI"), 33);
        grafo.agregarArista(n.get("FK"), n.get("FL"), 15);
        grafo.agregarArista(n.get("FL"), n.get("FK"), 15);
        grafo.agregarArista(n.get("FK"), n.get("GL"), 33);
        grafo.agregarArista(n.get("GL"), n.get("FK"), 33);
        grafo.agregarArista(n.get("FK"), n.get("GJ"), 33);
        grafo.agregarArista(n.get("GJ"), n.get("FK"), 33);
        grafo.agregarArista(n.get("FL"), n.get("FM"), 15);
        grafo.agregarArista(n.get("FM"), n.get("FL"), 15);
        grafo.agregarArista(n.get("FL"), n.get("GL"), 10);
        grafo.agregarArista(n.get("GL"), n.get("FL"), 30);
        grafo.agregarArista(n.get("FM"), n.get("GN"), 33);
        grafo.agregarArista(n.get("GN"), n.get("FM"), 33);
        grafo.agregarArista(n.get("FM"), n.get("GL"), 33);
        grafo.agregarArista(n.get("GL"), n.get("FM"), 33);
        grafo.agregarArista(n.get("FP"), n.get("GP"), 10);
        grafo.agregarArista(n.get("GP"), n.get("FP"), 30);
        grafo.agregarArista(n.get("FP"), n.get("GO"), 33);
        grafo.agregarArista(n.get("GO"), n.get("FP"), 33);
        grafo.agregarArista(n.get("FR"), n.get("GR"), 10);
        grafo.agregarArista(n.get("GR"), n.get("FR"), 30);
        grafo.agregarArista(n.get("GA"), n.get("HA"), 10);
        grafo.agregarArista(n.get("HA"), n.get("GA"), 30);
        grafo.agregarArista(n.get("GA"), n.get("HB"), 33);
        grafo.agregarArista(n.get("HB"), n.get("GA"), 33);
        grafo.agregarArista(n.get("GC"), n.get("GD"), 15);
        grafo.agregarArista(n.get("GD"), n.get("GC"), 15);
        grafo.agregarArista(n.get("GC"), n.get("HD"), 33);
        grafo.agregarArista(n.get("HD"), n.get("GC"), 33);
        grafo.agregarArista(n.get("GC"), n.get("HB"), 33);
        grafo.agregarArista(n.get("HB"), n.get("GC"), 33);
        grafo.agregarArista(n.get("GD"), n.get("GE"), 15);
        grafo.agregarArista(n.get("GE"), n.get("GD"), 15);
        grafo.agregarArista(n.get("GD"), n.get("HD"), 10);
        grafo.agregarArista(n.get("HD"), n.get("GD"), 30);
        grafo.agregarArista(n.get("GD"), n.get("HE"), 33);
        grafo.agregarArista(n.get("HE"), n.get("GD"), 33);
        grafo.agregarArista(n.get("GE"), n.get("GF"), 15);
        grafo.agregarArista(n.get("GF"), n.get("GE"), 15);
        grafo.agregarArista(n.get("GE"), n.get("HE"), 10);
        grafo.agregarArista(n.get("HE"), n.get("GE"), 30);
        grafo.agregarArista(n.get("GE"), n.get("HD"), 33);
        grafo.agregarArista(n.get("HD"), n.get("GE"), 33);
        grafo.agregarArista(n.get("GF"), n.get("HG"), 33);
        grafo.agregarArista(n.get("HG"), n.get("GF"), 33);
        grafo.agregarArista(n.get("GF"), n.get("HE"), 33);
        grafo.agregarArista(n.get("HE"), n.get("GF"), 33);
        grafo.agregarArista(n.get("GH"), n.get("GI"), 15);
        grafo.agregarArista(n.get("GI"), n.get("GH"), 15);
        grafo.agregarArista(n.get("GH"), n.get("HH"), 10);
        grafo.agregarArista(n.get("HH"), n.get("GH"), 30);
        grafo.agregarArista(n.get("GH"), n.get("HI"), 33);
        grafo.agregarArista(n.get("HI"), n.get("GH"), 33);
        grafo.agregarArista(n.get("GH"), n.get("HG"), 33);
        grafo.agregarArista(n.get("HG"), n.get("GH"), 33);
        grafo.agregarArista(n.get("GI"), n.get("GJ"), 15);
        grafo.agregarArista(n.get("GJ"), n.get("GI"), 15);
        grafo.agregarArista(n.get("GI"), n.get("HI"), 10);
        grafo.agregarArista(n.get("HI"), n.get("GI"), 30);
        grafo.agregarArista(n.get("GI"), n.get("HJ"), 33);
        grafo.agregarArista(n.get("HJ"), n.get("GI"), 33);
        grafo.agregarArista(n.get("GI"), n.get("HH"), 33);
        grafo.agregarArista(n.get("HH"), n.get("GI"), 33);
        grafo.agregarArista(n.get("GJ"), n.get("HJ"), 10);
        grafo.agregarArista(n.get("HJ"), n.get("GJ"), 30);
        grafo.agregarArista(n.get("GJ"), n.get("HK"), 33);
        grafo.agregarArista(n.get("HK"), n.get("GJ"), 33);
        grafo.agregarArista(n.get("GJ"), n.get("HI"), 33);
        grafo.agregarArista(n.get("HI"), n.get("GJ"), 33);
        grafo.agregarArista(n.get("GL"), n.get("HL"), 10);
        grafo.agregarArista(n.get("HL"), n.get("GL"), 30);
        grafo.agregarArista(n.get("GL"), n.get("HM"), 33);
        grafo.agregarArista(n.get("HM"), n.get("GL"), 33);
        grafo.agregarArista(n.get("GL"), n.get("HK"), 33);
        grafo.agregarArista(n.get("HK"), n.get("GL"), 33);
        grafo.agregarArista(n.get("GN"), n.get("GO"), 15);
        grafo.agregarArista(n.get("GO"), n.get("GN"), 15);
        grafo.agregarArista(n.get("GN"), n.get("HN"), 10);
        grafo.agregarArista(n.get("HN"), n.get("GN"), 30);
        grafo.agregarArista(n.get("GN"), n.get("HM"), 33);
        grafo.agregarArista(n.get("HM"), n.get("GN"), 33);
        grafo.agregarArista(n.get("GO"), n.get("GP"), 15);
        grafo.agregarArista(n.get("GP"), n.get("GO"), 15);
        grafo.agregarArista(n.get("GO"), n.get("HP"), 33);
        grafo.agregarArista(n.get("HP"), n.get("GO"), 33);
        grafo.agregarArista(n.get("GO"), n.get("HN"), 33);
        grafo.agregarArista(n.get("HN"), n.get("GO"), 33);
        grafo.agregarArista(n.get("GP"), n.get("HP"), 10);
        grafo.agregarArista(n.get("HP"), n.get("GP"), 30);
        grafo.agregarArista(n.get("GP"), n.get("HQ"), 33);
        grafo.agregarArista(n.get("HQ"), n.get("GP"), 33);
        grafo.agregarArista(n.get("GR"), n.get("HR"), 10);
        grafo.agregarArista(n.get("HR"), n.get("GR"), 30);
        grafo.agregarArista(n.get("GR"), n.get("HQ"), 33);
        grafo.agregarArista(n.get("HQ"), n.get("GR"), 33);
        grafo.agregarArista(n.get("HA"), n.get("HB"), 15);
        grafo.agregarArista(n.get("HB"), n.get("HA"), 15);
        grafo.agregarArista(n.get("HA"), n.get("IA"), 10);
        grafo.agregarArista(n.get("IA"), n.get("HA"), 30);
        grafo.agregarArista(n.get("HA"), n.get("IB"), 33);
        grafo.agregarArista(n.get("IB"), n.get("HA"), 33);
        grafo.agregarArista(n.get("HB"), n.get("IB"), 10);
        grafo.agregarArista(n.get("IB"), n.get("HB"), 30);
        grafo.agregarArista(n.get("HB"), n.get("IC"), 33);
        grafo.agregarArista(n.get("IC"), n.get("HB"), 33);
        grafo.agregarArista(n.get("HB"), n.get("IA"), 33);
        grafo.agregarArista(n.get("IA"), n.get("HB"), 33);
        grafo.agregarArista(n.get("HD"), n.get("HE"), 15);
        grafo.agregarArista(n.get("HE"), n.get("HD"), 15);
        grafo.agregarArista(n.get("HD"), n.get("IE"), 33);
        grafo.agregarArista(n.get("IE"), n.get("HD"), 33);
        grafo.agregarArista(n.get("HD"), n.get("IC"), 33);
        grafo.agregarArista(n.get("IC"), n.get("HD"), 33);
        grafo.agregarArista(n.get("HE"), n.get("IE"), 10);
        grafo.agregarArista(n.get("IE"), n.get("HE"), 30);
        grafo.agregarArista(n.get("HE"), n.get("IF"), 33);
        grafo.agregarArista(n.get("IF"), n.get("HE"), 33);
        grafo.agregarArista(n.get("HG"), n.get("HH"), 15);
        grafo.agregarArista(n.get("HH"), n.get("HG"), 15);
        grafo.agregarArista(n.get("HG"), n.get("IG"), 10);
        grafo.agregarArista(n.get("IG"), n.get("HG"), 30);
        grafo.agregarArista(n.get("HG"), n.get("IH"), 33);
        grafo.agregarArista(n.get("IH"), n.get("HG"), 33);
        grafo.agregarArista(n.get("HG"), n.get("IF"), 33);
        grafo.agregarArista(n.get("IF"), n.get("HG"), 33);
        grafo.agregarArista(n.get("HH"), n.get("HI"), 15);
        grafo.agregarArista(n.get("HI"), n.get("HH"), 15);
        grafo.agregarArista(n.get("HH"), n.get("IH"), 10);
        grafo.agregarArista(n.get("IH"), n.get("HH"), 30);
        grafo.agregarArista(n.get("HH"), n.get("IG"), 33);
        grafo.agregarArista(n.get("IG"), n.get("HH"), 33);
        grafo.agregarArista(n.get("HI"), n.get("HJ"), 15);
        grafo.agregarArista(n.get("HJ"), n.get("HI"), 15);
        grafo.agregarArista(n.get("HI"), n.get("IJ"), 33);
        grafo.agregarArista(n.get("IJ"), n.get("HI"), 33);
        grafo.agregarArista(n.get("HI"), n.get("IH"), 33);
        grafo.agregarArista(n.get("IH"), n.get("HI"), 33);
        grafo.agregarArista(n.get("HJ"), n.get("HK"), 15);
        grafo.agregarArista(n.get("HK"), n.get("HJ"), 15);
        grafo.agregarArista(n.get("HJ"), n.get("IJ"), 10);
        grafo.agregarArista(n.get("IJ"), n.get("HJ"), 30);
        grafo.agregarArista(n.get("HJ"), n.get("IK"), 33);
        grafo.agregarArista(n.get("IK"), n.get("HJ"), 33);
        grafo.agregarArista(n.get("HK"), n.get("HL"), 15);
        grafo.agregarArista(n.get("HL"), n.get("HK"), 15);
        grafo.agregarArista(n.get("HK"), n.get("IK"), 10);
        grafo.agregarArista(n.get("IK"), n.get("HK"), 30);
        grafo.agregarArista(n.get("HK"), n.get("IL"), 33);
        grafo.agregarArista(n.get("IL"), n.get("HK"), 33);
        grafo.agregarArista(n.get("HK"), n.get("IJ"), 33);
        grafo.agregarArista(n.get("IJ"), n.get("HK"), 33);
        grafo.agregarArista(n.get("HL"), n.get("HM"), 15);
        grafo.agregarArista(n.get("HM"), n.get("HL"), 15);
        grafo.agregarArista(n.get("HL"), n.get("IL"), 10);
        grafo.agregarArista(n.get("IL"), n.get("HL"), 30);
        grafo.agregarArista(n.get("HL"), n.get("IK"), 33);
        grafo.agregarArista(n.get("IK"), n.get("HL"), 33);
        grafo.agregarArista(n.get("HM"), n.get("HN"), 15);
        grafo.agregarArista(n.get("HN"), n.get("HM"), 15);
        grafo.agregarArista(n.get("HM"), n.get("IN"), 33);
        grafo.agregarArista(n.get("IN"), n.get("HM"), 33);
        grafo.agregarArista(n.get("HM"), n.get("IL"), 33);
        grafo.agregarArista(n.get("IL"), n.get("HM"), 33);
        grafo.agregarArista(n.get("HN"), n.get("IN"), 10);
        grafo.agregarArista(n.get("IN"), n.get("HN"), 30);
        grafo.agregarArista(n.get("HN"), n.get("IO"), 33);
        grafo.agregarArista(n.get("IO"), n.get("HN"), 33);
        grafo.agregarArista(n.get("HP"), n.get("HQ"), 15);
        grafo.agregarArista(n.get("HQ"), n.get("HP"), 15);
        grafo.agregarArista(n.get("HP"), n.get("IO"), 33);
        grafo.agregarArista(n.get("IO"), n.get("HP"), 33);
        grafo.agregarArista(n.get("HQ"), n.get("HR"), 15);
        grafo.agregarArista(n.get("HR"), n.get("HQ"), 15);
        grafo.agregarArista(n.get("HQ"), n.get("IQ"), 10);
        grafo.agregarArista(n.get("IQ"), n.get("HQ"), 30);
        grafo.agregarArista(n.get("IA"), n.get("IB"), 15);
        grafo.agregarArista(n.get("IB"), n.get("IA"), 15);
        grafo.agregarArista(n.get("IA"), n.get("JB"), 33);
        grafo.agregarArista(n.get("JB"), n.get("IA"), 33);
        grafo.agregarArista(n.get("IB"), n.get("IC"), 15);
        grafo.agregarArista(n.get("IC"), n.get("IB"), 15);
        grafo.agregarArista(n.get("IB"), n.get("JB"), 10);
        grafo.agregarArista(n.get("JB"), n.get("IB"), 30);
        grafo.agregarArista(n.get("IB"), n.get("JC"), 33);
        grafo.agregarArista(n.get("JC"), n.get("IB"), 33);
        grafo.agregarArista(n.get("IC"), n.get("JC"), 10);
        grafo.agregarArista(n.get("JC"), n.get("IC"), 30);
        grafo.agregarArista(n.get("IC"), n.get("JD"), 33);
        grafo.agregarArista(n.get("JD"), n.get("IC"), 33);
        grafo.agregarArista(n.get("IC"), n.get("JB"), 33);
        grafo.agregarArista(n.get("JB"), n.get("IC"), 33);
        grafo.agregarArista(n.get("IE"), n.get("IF"), 15);
        grafo.agregarArista(n.get("IF"), n.get("IE"), 15);
        grafo.agregarArista(n.get("IE"), n.get("JE"), 10);
        grafo.agregarArista(n.get("JE"), n.get("IE"), 30);
        grafo.agregarArista(n.get("IE"), n.get("JF"), 33);
        grafo.agregarArista(n.get("JF"), n.get("IE"), 33);
        grafo.agregarArista(n.get("IE"), n.get("JD"), 33);
        grafo.agregarArista(n.get("JD"), n.get("IE"), 33);
        grafo.agregarArista(n.get("IF"), n.get("IG"), 15);
        grafo.agregarArista(n.get("IG"), n.get("IF"), 15);
        grafo.agregarArista(n.get("IF"), n.get("JF"), 10);
        grafo.agregarArista(n.get("JF"), n.get("IF"), 30);
        grafo.agregarArista(n.get("IF"), n.get("JG"), 33);
        grafo.agregarArista(n.get("JG"), n.get("IF"), 33);
        grafo.agregarArista(n.get("IF"), n.get("JE"), 33);
        grafo.agregarArista(n.get("JE"), n.get("IF"), 33);
        grafo.agregarArista(n.get("IG"), n.get("IH"), 15);
        grafo.agregarArista(n.get("IH"), n.get("IG"), 15);
        grafo.agregarArista(n.get("IG"), n.get("JG"), 10);
        grafo.agregarArista(n.get("JG"), n.get("IG"), 30);
        grafo.agregarArista(n.get("IG"), n.get("JH"), 33);
        grafo.agregarArista(n.get("JH"), n.get("IG"), 33);
        grafo.agregarArista(n.get("IG"), n.get("JF"), 33);
        grafo.agregarArista(n.get("JF"), n.get("IG"), 33);
        grafo.agregarArista(n.get("IH"), n.get("JH"), 10);
        grafo.agregarArista(n.get("JH"), n.get("IH"), 30);
        grafo.agregarArista(n.get("IH"), n.get("JI"), 33);
        grafo.agregarArista(n.get("JI"), n.get("IH"), 33);
        grafo.agregarArista(n.get("IH"), n.get("JG"), 33);
        grafo.agregarArista(n.get("JG"), n.get("IH"), 33);
        grafo.agregarArista(n.get("IJ"), n.get("IK"), 15);
        grafo.agregarArista(n.get("IK"), n.get("IJ"), 15);
        grafo.agregarArista(n.get("IJ"), n.get("JJ"), 10);
        grafo.agregarArista(n.get("JJ"), n.get("IJ"), 30);
        grafo.agregarArista(n.get("IJ"), n.get("JK"), 33);
        grafo.agregarArista(n.get("JK"), n.get("IJ"), 33);
        grafo.agregarArista(n.get("IJ"), n.get("JI"), 33);
        grafo.agregarArista(n.get("JI"), n.get("IJ"), 33);
        grafo.agregarArista(n.get("IK"), n.get("IL"), 15);
        grafo.agregarArista(n.get("IL"), n.get("IK"), 15);
        grafo.agregarArista(n.get("IK"), n.get("JK"), 10);
        grafo.agregarArista(n.get("JK"), n.get("IK"), 30);
        grafo.agregarArista(n.get("IK"), n.get("JJ"), 33);
        grafo.agregarArista(n.get("JJ"), n.get("IK"), 33);
        grafo.agregarArista(n.get("IL"), n.get("JM"), 33);
        grafo.agregarArista(n.get("JM"), n.get("IL"), 33);
        grafo.agregarArista(n.get("IL"), n.get("JK"), 33);
        grafo.agregarArista(n.get("JK"), n.get("IL"), 33);
        grafo.agregarArista(n.get("IN"), n.get("IO"), 15);
        grafo.agregarArista(n.get("IO"), n.get("IN"), 15);
        grafo.agregarArista(n.get("IN"), n.get("JO"), 33);
        grafo.agregarArista(n.get("JO"), n.get("IN"), 33);
        grafo.agregarArista(n.get("IN"), n.get("JM"), 33);
        grafo.agregarArista(n.get("JM"), n.get("IN"), 33);
        grafo.agregarArista(n.get("IO"), n.get("JO"), 10);
        grafo.agregarArista(n.get("JO"), n.get("IO"), 30);
        grafo.agregarArista(n.get("IO"), n.get("JP"), 33);
        grafo.agregarArista(n.get("JP"), n.get("IO"), 33);
        grafo.agregarArista(n.get("IQ"), n.get("JP"), 33);
        grafo.agregarArista(n.get("JP"), n.get("IQ"), 33);
        grafo.agregarArista(n.get("IQ"), n.get("JR"), 33);
        grafo.agregarArista(n.get("JR"), n.get("IQ"), 33);
        grafo.agregarArista(n.get("IQ"), n.get("JQ"), 10);
        grafo.agregarArista(n.get("JQ"), n.get("IQ"), 30);
        grafo.agregarArista(n.get("JB"), n.get("JC"), 15);
        grafo.agregarArista(n.get("JC"), n.get("JB"), 15);
        grafo.agregarArista(n.get("JB"), n.get("KB"), 10);
        grafo.agregarArista(n.get("KB"), n.get("JB"), 30);
        grafo.agregarArista(n.get("JB"), n.get("KA"), 33);
        grafo.agregarArista(n.get("KA"), n.get("JB"), 33);
        grafo.agregarArista(n.get("JC"), n.get("JD"), 15);
        grafo.agregarArista(n.get("JD"), n.get("JC"), 15);
        grafo.agregarArista(n.get("JC"), n.get("KD"), 33);
        grafo.agregarArista(n.get("KD"), n.get("JC"), 33);
        grafo.agregarArista(n.get("JC"), n.get("KB"), 33);
        grafo.agregarArista(n.get("KB"), n.get("JC"), 33);
        grafo.agregarArista(n.get("JD"), n.get("JE"), 15);
        grafo.agregarArista(n.get("JE"), n.get("JD"), 15);
        grafo.agregarArista(n.get("JD"), n.get("KD"), 10);
        grafo.agregarArista(n.get("KD"), n.get("JD"), 30);
        grafo.agregarArista(n.get("JE"), n.get("JF"), 15);
        grafo.agregarArista(n.get("JF"), n.get("JE"), 15);
        grafo.agregarArista(n.get("JE"), n.get("KD"), 33);
        grafo.agregarArista(n.get("KD"), n.get("JE"), 33);
        grafo.agregarArista(n.get("JF"), n.get("JG"), 15);
        grafo.agregarArista(n.get("JG"), n.get("JF"), 15);
        grafo.agregarArista(n.get("JF"), n.get("KG"), 33);
        grafo.agregarArista(n.get("KG"), n.get("JF"), 33);
        grafo.agregarArista(n.get("JG"), n.get("JH"), 15);
        grafo.agregarArista(n.get("JH"), n.get("JG"), 15);
        grafo.agregarArista(n.get("JG"), n.get("KG"), 10);
        grafo.agregarArista(n.get("KG"), n.get("JG"), 30);
        grafo.agregarArista(n.get("JH"), n.get("JI"), 15);
        grafo.agregarArista(n.get("JI"), n.get("JH"), 15);
        grafo.agregarArista(n.get("JH"), n.get("KI"), 33);
        grafo.agregarArista(n.get("KI"), n.get("JH"), 33);
        grafo.agregarArista(n.get("JH"), n.get("KG"), 33);
        grafo.agregarArista(n.get("KG"), n.get("JH"), 33);
        grafo.agregarArista(n.get("JI"), n.get("JJ"), 15);
        grafo.agregarArista(n.get("JJ"), n.get("JI"), 15);
        grafo.agregarArista(n.get("JI"), n.get("KI"), 10);
        grafo.agregarArista(n.get("KI"), n.get("JI"), 30);
        grafo.agregarArista(n.get("JJ"), n.get("JK"), 15);
        grafo.agregarArista(n.get("JK"), n.get("JJ"), 15);
        grafo.agregarArista(n.get("JJ"), n.get("KK"), 33);
        grafo.agregarArista(n.get("KK"), n.get("JJ"), 33);
        grafo.agregarArista(n.get("JJ"), n.get("KI"), 33);
        grafo.agregarArista(n.get("KI"), n.get("JJ"), 33);
        grafo.agregarArista(n.get("JK"), n.get("KK"), 10);
        grafo.agregarArista(n.get("KK"), n.get("JK"), 30);
        grafo.agregarArista(n.get("JK"), n.get("KL"), 33);
        grafo.agregarArista(n.get("KL"), n.get("JK"), 33);
        grafo.agregarArista(n.get("JM"), n.get("KM"), 10);
        grafo.agregarArista(n.get("KM"), n.get("JM"), 30);
        grafo.agregarArista(n.get("JM"), n.get("KN"), 33);
        grafo.agregarArista(n.get("KN"), n.get("JM"), 33);
        grafo.agregarArista(n.get("JM"), n.get("KL"), 33);
        grafo.agregarArista(n.get("KL"), n.get("JM"), 33);
        grafo.agregarArista(n.get("JO"), n.get("JP"), 15);
        grafo.agregarArista(n.get("JP"), n.get("JO"), 15);
        grafo.agregarArista(n.get("JO"), n.get("KO"), 10);
        grafo.agregarArista(n.get("KO"), n.get("JO"), 30);
        grafo.agregarArista(n.get("JO"), n.get("KN"), 33);
        grafo.agregarArista(n.get("KN"), n.get("JO"), 33);
        grafo.agregarArista(n.get("JP"), n.get("JQ"), 15);
        grafo.agregarArista(n.get("JQ"), n.get("JP"), 15);
        grafo.agregarArista(n.get("JP"), n.get("KQ"), 33);
        grafo.agregarArista(n.get("KQ"), n.get("JP"), 33);
        grafo.agregarArista(n.get("JP"), n.get("KO"), 33);
        grafo.agregarArista(n.get("KO"), n.get("JP"), 33);
        grafo.agregarArista(n.get("JQ"), n.get("JR"), 15);
        grafo.agregarArista(n.get("JR"), n.get("JQ"), 15);
        grafo.agregarArista(n.get("JQ"), n.get("KQ"), 10);
        grafo.agregarArista(n.get("KQ"), n.get("JQ"), 30);
        grafo.agregarArista(n.get("JQ"), n.get("KR"), 33);
        grafo.agregarArista(n.get("KR"), n.get("JQ"), 33);
        grafo.agregarArista(n.get("JR"), n.get("KR"), 10);
        grafo.agregarArista(n.get("KR"), n.get("JR"), 30);
        grafo.agregarArista(n.get("JR"), n.get("KQ"), 33);
        grafo.agregarArista(n.get("KQ"), n.get("JR"), 33);
        grafo.agregarArista(n.get("KA"), n.get("KB"), 15);
        grafo.agregarArista(n.get("KB"), n.get("KA"), 15);
        grafo.agregarArista(n.get("KA"), n.get("LB"), 33);
        grafo.agregarArista(n.get("LB"), n.get("KA"), 33);
        grafo.agregarArista(n.get("KB"), n.get("LB"), 10);
        grafo.agregarArista(n.get("LB"), n.get("KB"), 30);
        grafo.agregarArista(n.get("KD"), n.get("LD"), 10);
        grafo.agregarArista(n.get("LD"), n.get("KD"), 30);
        grafo.agregarArista(n.get("KD"), n.get("LE"), 33);
        grafo.agregarArista(n.get("LE"), n.get("KD"), 33);
        grafo.agregarArista(n.get("KG"), n.get("LG"), 10);
        grafo.agregarArista(n.get("LG"), n.get("KG"), 30);
        grafo.agregarArista(n.get("KG"), n.get("LF"), 33);
        grafo.agregarArista(n.get("LF"), n.get("KG"), 33);
        grafo.agregarArista(n.get("KI"), n.get("LI"), 10);
        grafo.agregarArista(n.get("lI"), n.get("kI"), 30);
        grafo.agregarArista(n.get("KI"), n.get("LJ"), 33);
        grafo.agregarArista(n.get("LJ"), n.get("KI"), 33);
        grafo.agregarArista(n.get("KK"), n.get("KL"), 15);
        grafo.agregarArista(n.get("KL"), n.get("KK"), 15);
        grafo.agregarArista(n.get("KK"), n.get("LJ"), 33);
        grafo.agregarArista(n.get("LJ"), n.get("KK"), 33);
        grafo.agregarArista(n.get("KK"), n.get("LK"), 10);
        grafo.agregarArista(n.get("LK"), n.get("KK"), 30);
        grafo.agregarArista(n.get("KL"), n.get("KM"), 15);
        grafo.agregarArista(n.get("KM"), n.get("KL"), 15);
        grafo.agregarArista(n.get("KL"), n.get("LK"), 33);
        grafo.agregarArista(n.get("LK"), n.get("KL"), 33);
        grafo.agregarArista(n.get("KM"), n.get("KN"), 15);
        grafo.agregarArista(n.get("KN"), n.get("KM"), 15);
        grafo.agregarArista(n.get("KM"), n.get("LN"), 33);
        grafo.agregarArista(n.get("LN"), n.get("KM"), 33);
        grafo.agregarArista(n.get("KN"), n.get("KO"), 15);
        grafo.agregarArista(n.get("KO"), n.get("KN"), 15);
        grafo.agregarArista(n.get("KN"), n.get("LN"), 10);
        grafo.agregarArista(n.get("LN"), n.get("KN"), 30);
        grafo.agregarArista(n.get("KN"), n.get("LO"), 33);
        grafo.agregarArista(n.get("LO"), n.get("KN"), 33);
        grafo.agregarArista(n.get("KO"), n.get("LO"), 10);
        grafo.agregarArista(n.get("LO"), n.get("KO"), 30);
        grafo.agregarArista(n.get("KO"), n.get("LN"), 33);
        grafo.agregarArista(n.get("LN"), n.get("KO"), 33);
        grafo.agregarArista(n.get("KQ"), n.get("KR"), 15);
        grafo.agregarArista(n.get("KR"), n.get("KQ"), 15);
        grafo.agregarArista(n.get("KQ"), n.get("LR"), 33);
        grafo.agregarArista(n.get("LR"), n.get("KQ"), 33);
        grafo.agregarArista(n.get("KR"), n.get("LR"), 10);
        grafo.agregarArista(n.get("LR"), n.get("KR"), 30);
        grafo.agregarArista(n.get("LB"), n.get("MC"), 33);
        grafo.agregarArista(n.get("MC"), n.get("LB"), 33);
        grafo.agregarArista(n.get("LB"), n.get("MA"), 33);
        grafo.agregarArista(n.get("MA"), n.get("LB"), 33);
        grafo.agregarArista(n.get("LD"), n.get("LE"), 15);
        grafo.agregarArista(n.get("LE"), n.get("LD"), 15);
        grafo.agregarArista(n.get("LD"), n.get("MD"), 10);
        grafo.agregarArista(n.get("MD"), n.get("LD"), 30);
        grafo.agregarArista(n.get("LD"), n.get("MC"), 33);
        grafo.agregarArista(n.get("MC"), n.get("LD"), 33);
        grafo.agregarArista(n.get("LE"), n.get("LF"), 15);
        grafo.agregarArista(n.get("LF"), n.get("LE"), 15);
        grafo.agregarArista(n.get("LE"), n.get("MF"), 33);
        grafo.agregarArista(n.get("MF"), n.get("LE"), 33);
        grafo.agregarArista(n.get("LE"), n.get("MD"), 33);
        grafo.agregarArista(n.get("MD"), n.get("LE"), 33);
        grafo.agregarArista(n.get("LF"), n.get("MF"), 10);
        grafo.agregarArista(n.get("MF"), n.get("LF"), 30);
        grafo.agregarArista(n.get("LG"), n.get("LF"), 15);
        grafo.agregarArista(n.get("LF"), n.get("LG"), 15);
        grafo.agregarArista(n.get("LG"), n.get("MF"), 33);
        grafo.agregarArista(n.get("MF"), n.get("LG"), 33);
        grafo.agregarArista(n.get("LG"), n.get("MH"), 33);
        grafo.agregarArista(n.get("MH"), n.get("LG"), 33);
        grafo.agregarArista(n.get("LI"), n.get("LJ"), 15);
        grafo.agregarArista(n.get("LJ"), n.get("LI"), 15);
        grafo.agregarArista(n.get("LI"), n.get("MI"), 10);
        grafo.agregarArista(n.get("MI"), n.get("LI"), 30);
        grafo.agregarArista(n.get("LI"), n.get("MJ"), 33);
        grafo.agregarArista(n.get("MJ"), n.get("LI"), 33);
        grafo.agregarArista(n.get("LI"), n.get("MH"), 33);
        grafo.agregarArista(n.get("MH"), n.get("LI"), 33);
        grafo.agregarArista(n.get("LJ"), n.get("MJ"), 10);
        grafo.agregarArista(n.get("MJ"), n.get("LJ"), 30);
        grafo.agregarArista(n.get("LJ"), n.get("MK"), 33);
        grafo.agregarArista(n.get("MK"), n.get("LJ"), 33);
        grafo.agregarArista(n.get("LJ"), n.get("MI"), 33);
        grafo.agregarArista(n.get("MI"), n.get("LJ"), 33);
        grafo.agregarArista(n.get("LJ"), n.get("LK"), 15);
        grafo.agregarArista(n.get("LK"), n.get("LJ"), 15);
        grafo.agregarArista(n.get("LK"), n.get("MJ"), 33);
        grafo.agregarArista(n.get("MJ"), n.get("LK"), 33);
        grafo.agregarArista(n.get("LK"), n.get("ML"), 33);
        grafo.agregarArista(n.get("ML"), n.get("LK"), 33);
        grafo.agregarArista(n.get("LK"), n.get("MK"), 10);
        grafo.agregarArista(n.get("MK"), n.get("LK"), 30);
        grafo.agregarArista(n.get("LN"), n.get("LO"), 15);
        grafo.agregarArista(n.get("LO"), n.get("LN"), 15);
        grafo.agregarArista(n.get("LN"), n.get("MM"), 33);
        grafo.agregarArista(n.get("MM"), n.get("LN"), 33);
        grafo.agregarArista(n.get("LO"), n.get("MP"), 33);
        grafo.agregarArista(n.get("MP"), n.get("LO"), 33);
        grafo.agregarArista(n.get("LO"), n.get("LP"), 15);
        grafo.agregarArista(n.get("LP"), n.get("LO"), 15);
        grafo.agregarArista(n.get("LP"), n.get("MP"), 10);
        grafo.agregarArista(n.get("MP"), n.get("LP"), 30);
        grafo.agregarArista(n.get("LP"), n.get("KO"), 33);
        grafo.agregarArista(n.get("KO"), n.get("LP"), 33);
        grafo.agregarArista(n.get("LP"), n.get("KQ"), 33);
        grafo.agregarArista(n.get("KQ"), n.get("LP"), 33);
        grafo.agregarArista(n.get("MA"), n.get("NB"), 33);
        grafo.agregarArista(n.get("NB"), n.get("MA"), 33);
        grafo.agregarArista(n.get("MC"), n.get("MD"), 15);
        grafo.agregarArista(n.get("MD"), n.get("MC"), 15);
        grafo.agregarArista(n.get("MC"), n.get("NC"), 10);
        grafo.agregarArista(n.get("NC"), n.get("MC"), 30);
        grafo.agregarArista(n.get("MC"), n.get("ND"), 33);
        grafo.agregarArista(n.get("ND"), n.get("MC"), 33);
        grafo.agregarArista(n.get("MC"), n.get("NB"), 33);
        grafo.agregarArista(n.get("NB"), n.get("MC"), 33);
        grafo.agregarArista(n.get("MD"), n.get("ND"), 10);
        grafo.agregarArista(n.get("ND"), n.get("MD"), 30);
        grafo.agregarArista(n.get("MD"), n.get("NE"), 33);
        grafo.agregarArista(n.get("NE"), n.get("MD"), 33);
        grafo.agregarArista(n.get("MD"), n.get("NC"), 33);
        grafo.agregarArista(n.get("NC"), n.get("MD"), 33);
        grafo.agregarArista(n.get("MF"), n.get("NF"), 10);
        grafo.agregarArista(n.get("NF"), n.get("MF"), 30);
        grafo.agregarArista(n.get("MF"), n.get("NG"), 33);
        grafo.agregarArista(n.get("NG"), n.get("MF"), 33);
        grafo.agregarArista(n.get("MF"), n.get("NE"), 33);
        grafo.agregarArista(n.get("NE"), n.get("MF"), 33);
        grafo.agregarArista(n.get("MH"), n.get("MI"), 15);
        grafo.agregarArista(n.get("MI"), n.get("MH"), 15);
        grafo.agregarArista(n.get("MH"), n.get("NH"), 10);
        grafo.agregarArista(n.get("NH"), n.get("MH"), 30);
        grafo.agregarArista(n.get("MH"), n.get("NI"), 33);
        grafo.agregarArista(n.get("NI"), n.get("MH"), 33);
        grafo.agregarArista(n.get("MH"), n.get("NG"), 33);
        grafo.agregarArista(n.get("NG"), n.get("MH"), 33);
        grafo.agregarArista(n.get("MI"), n.get("MJ"), 15);
        grafo.agregarArista(n.get("MJ"), n.get("MI"), 15);
        grafo.agregarArista(n.get("MI"), n.get("NI"), 10);
        grafo.agregarArista(n.get("NI"), n.get("MI"), 30);
        grafo.agregarArista(n.get("MI"), n.get("NH"), 33);
        grafo.agregarArista(n.get("NH"), n.get("MI"), 33);
        grafo.agregarArista(n.get("MJ"), n.get("MK"), 15);
        grafo.agregarArista(n.get("MK"), n.get("MJ"), 15);
        grafo.agregarArista(n.get("MJ"), n.get("NK"), 33);
        grafo.agregarArista(n.get("NK"), n.get("MJ"), 33);
        grafo.agregarArista(n.get("MJ"), n.get("NI"), 33);
        grafo.agregarArista(n.get("NI"), n.get("MJ"), 33);
        grafo.agregarArista(n.get("MK"), n.get("ML"), 15);
        grafo.agregarArista(n.get("ML"), n.get("MK"), 15);
        grafo.agregarArista(n.get("MK"), n.get("NK"), 10);
        grafo.agregarArista(n.get("NK"), n.get("MK"), 30);
        grafo.agregarArista(n.get("MK"), n.get("NL"), 33);
        grafo.agregarArista(n.get("NL"), n.get("MK"), 33);
        grafo.agregarArista(n.get("ML"), n.get("MM"), 15);
        grafo.agregarArista(n.get("MM"), n.get("ML"), 15);
        grafo.agregarArista(n.get("ML"), n.get("NL"), 10);
        grafo.agregarArista(n.get("NL"), n.get("ML"), 30);
        grafo.agregarArista(n.get("ML"), n.get("NK"), 33);
        grafo.agregarArista(n.get("NK"), n.get("ML"), 33);
        grafo.agregarArista(n.get("MM"), n.get("NN"), 33);
        grafo.agregarArista(n.get("NN"), n.get("MM"), 33);
        grafo.agregarArista(n.get("MM"), n.get("NL"), 33);
        grafo.agregarArista(n.get("NL"), n.get("MM"), 33);
        grafo.agregarArista(n.get("MN"), n.get("MM"), 15);
        grafo.agregarArista(n.get("MM"), n.get("MN"), 15);
        grafo.agregarArista(n.get("MN"), n.get("LN"), 10);
        grafo.agregarArista(n.get("LN"), n.get("MN"), 30);
        grafo.agregarArista(n.get("MN"), n.get("NN"), 10);
        grafo.agregarArista(n.get("NN"), n.get("MN"), 30);
        grafo.agregarArista(n.get("MN"), n.get("LO"), 33);
        grafo.agregarArista(n.get("LO"), n.get("MN"), 33);
        grafo.agregarArista(n.get("MQ"), n.get("MP"), 15);
        grafo.agregarArista(n.get("MP"), n.get("MQ"), 15);
        grafo.agregarArista(n.get("MQ"), n.get("LP"), 33);
        grafo.agregarArista(n.get("LP"), n.get("MQ"), 33);
        grafo.agregarArista(n.get("MQ"), n.get("LR"), 33);
        grafo.agregarArista(n.get("LR"), n.get("MQ"), 33);
        grafo.agregarArista(n.get("MQ"), n.get("NR"), 33);
        grafo.agregarArista(n.get("NR"), n.get("MQ"), 33);
        grafo.agregarArista(n.get("MQ"), n.get("NQ"), 10);
        grafo.agregarArista(n.get("NQ"), n.get("MQ"), 30);
        grafo.agregarArista(n.get("NQ"), n.get("MP"), 33);
        grafo.agregarArista(n.get("MP"), n.get("NQ"), 33);
        grafo.agregarArista(n.get("NQ"), n.get("NR"), 15);
        grafo.agregarArista(n.get("NR"), n.get("NQ"), 15);
        grafo.agregarArista(n.get("NQ"), n.get("OP"), 33);
        grafo.agregarArista(n.get("OP"), n.get("NQ"), 33);
        grafo.agregarArista(n.get("NQ"), n.get("OR"), 33);
        grafo.agregarArista(n.get("OR"), n.get("NQ"), 33);
        grafo.agregarArista(n.get("NQ"), n.get("OQ"), 10);
        grafo.agregarArista(n.get("OQ"), n.get("NQ"), 30);
        grafo.agregarArista(n.get("NB"), n.get("NC"), 15);
        grafo.agregarArista(n.get("NC"), n.get("NB"), 15);
        grafo.agregarArista(n.get("NB"), n.get("OB"), 10);
        grafo.agregarArista(n.get("OB"), n.get("NB"), 30);
        grafo.agregarArista(n.get("NB"), n.get("OC"), 33);
        grafo.agregarArista(n.get("OC"), n.get("NB"), 33);
        grafo.agregarArista(n.get("NB"), n.get("OA"), 33);
        grafo.agregarArista(n.get("OA"), n.get("NB"), 33);
        grafo.agregarArista(n.get("NC"), n.get("ND"), 15);
        grafo.agregarArista(n.get("ND"), n.get("NC"), 15);
        grafo.agregarArista(n.get("NC"), n.get("OC"), 10);
        grafo.agregarArista(n.get("OC"), n.get("NC"), 30);
        grafo.agregarArista(n.get("NC"), n.get("OD"), 33);
        grafo.agregarArista(n.get("OD"), n.get("NC"), 33);
        grafo.agregarArista(n.get("NC"), n.get("OB"), 33);
        grafo.agregarArista(n.get("OB"), n.get("NC"), 33);
        grafo.agregarArista(n.get("ND"), n.get("NE"), 15);
        grafo.agregarArista(n.get("NE"), n.get("ND"), 15);
        grafo.agregarArista(n.get("ND"), n.get("OD"), 10);
        grafo.agregarArista(n.get("OD"), n.get("ND"), 30);
        grafo.agregarArista(n.get("ND"), n.get("OE"), 33);
        grafo.agregarArista(n.get("OE"), n.get("ND"), 33);
        grafo.agregarArista(n.get("ND"), n.get("OC"), 33);
        grafo.agregarArista(n.get("OC"), n.get("ND"), 33);
        grafo.agregarArista(n.get("NE"), n.get("NF"), 15);
        grafo.agregarArista(n.get("NF"), n.get("NE"), 15);
        grafo.agregarArista(n.get("NE"), n.get("OE"), 10);
        grafo.agregarArista(n.get("OE"), n.get("NE"), 30);
        grafo.agregarArista(n.get("NE"), n.get("OD"), 33);
        grafo.agregarArista(n.get("OD"), n.get("NE"), 33);
        grafo.agregarArista(n.get("NF"), n.get("NG"), 15);
        grafo.agregarArista(n.get("NG"), n.get("NF"), 15);
        grafo.agregarArista(n.get("NF"), n.get("OG"), 33);
        grafo.agregarArista(n.get("OG"), n.get("NF"), 33);
        grafo.agregarArista(n.get("NF"), n.get("OE"), 33);
        grafo.agregarArista(n.get("OE"), n.get("NF"), 33);
        grafo.agregarArista(n.get("NG"), n.get("NH"), 15);
        grafo.agregarArista(n.get("NH"), n.get("NG"), 15);
        grafo.agregarArista(n.get("NG"), n.get("OG"), 10);
        grafo.agregarArista(n.get("OG"), n.get("NG"), 30);
        grafo.agregarArista(n.get("NH"), n.get("NI"), 15);
        grafo.agregarArista(n.get("NI"), n.get("NH"), 15);
        grafo.agregarArista(n.get("NH"), n.get("OI"), 33);
        grafo.agregarArista(n.get("OI"), n.get("NH"), 33);
        grafo.agregarArista(n.get("NH"), n.get("OG"), 33);
        grafo.agregarArista(n.get("OG"), n.get("NH"), 33);
        grafo.agregarArista(n.get("NI"), n.get("OI"), 10);
        grafo.agregarArista(n.get("OI"), n.get("NI"), 30);
        grafo.agregarArista(n.get("NI"), n.get("OJ"), 33);
        grafo.agregarArista(n.get("OJ"), n.get("NI"), 33);
        grafo.agregarArista(n.get("NK"), n.get("NL"), 15);
        grafo.agregarArista(n.get("NL"), n.get("NK"), 15);
        grafo.agregarArista(n.get("NK"), n.get("OL"), 33);
        grafo.agregarArista(n.get("OL"), n.get("NK"), 33);
        grafo.agregarArista(n.get("NK"), n.get("OJ"), 33);
        grafo.agregarArista(n.get("OJ"), n.get("NK"), 33);
        grafo.agregarArista(n.get("NL"), n.get("OL"), 10);
        grafo.agregarArista(n.get("OL"), n.get("NL"), 30);
        grafo.agregarArista(n.get("NL"), n.get("OM"), 33);
        grafo.agregarArista(n.get("OM"), n.get("NL"), 33);
        grafo.agregarArista(n.get("NN"), n.get("OO"), 33);
        grafo.agregarArista(n.get("OO"), n.get("NN"), 33);
        grafo.agregarArista(n.get("NN"), n.get("OM"), 33);
        grafo.agregarArista(n.get("OM"), n.get("NN"), 33);
        grafo.agregarArista(n.get("NO"), n.get("NN"), 15);
        grafo.agregarArista(n.get("NN"), n.get("NO"), 15);
        grafo.agregarArista(n.get("NO"), n.get("MN"), 33);
        grafo.agregarArista(n.get("MN"), n.get("NO"), 33);
        grafo.agregarArista(n.get("NO"), n.get("OP"), 33);
        grafo.agregarArista(n.get("OP"), n.get("NO"), 33);
        grafo.agregarArista(n.get("NO"), n.get("OO"), 10);
        grafo.agregarArista(n.get("NO"), n.get("OO"), 30);
        grafo.agregarArista(n.get("NO"), n.get("MP"), 33);
        grafo.agregarArista(n.get("MP"), n.get("NO"), 33);
        grafo.agregarArista(n.get("NR"), n.get("OR"), 10);
        grafo.agregarArista(n.get("OR"), n.get("NR"), 30);
        grafo.agregarArista(n.get("NR"), n.get("OQ"), 33);
        grafo.agregarArista(n.get("OQ"), n.get("NR"), 33);
        grafo.agregarArista(n.get("OA"), n.get("OB"), 15);
        grafo.agregarArista(n.get("OB"), n.get("OA"), 15);
        grafo.agregarArista(n.get("OA"), n.get("PA"), 10);
        grafo.agregarArista(n.get("PA"), n.get("OA"), 30);
        grafo.agregarArista(n.get("OB"), n.get("OC"), 15);
        grafo.agregarArista(n.get("OC"), n.get("OB"), 15);
        grafo.agregarArista(n.get("OB"), n.get("PC"), 33);
        grafo.agregarArista(n.get("PC"), n.get("OB"), 33);
        grafo.agregarArista(n.get("OB"), n.get("PA"), 33);
        grafo.agregarArista(n.get("PA"), n.get("OB"), 33);
        grafo.agregarArista(n.get("OC"), n.get("OD"), 15);
        grafo.agregarArista(n.get("OD"), n.get("OC"), 15);
        grafo.agregarArista(n.get("OC"), n.get("PC"), 10);
        grafo.agregarArista(n.get("PC"), n.get("OC"), 30);
        grafo.agregarArista(n.get("OD"), n.get("OE"), 15);
        grafo.agregarArista(n.get("OE"), n.get("OD"), 15);
        grafo.agregarArista(n.get("OD"), n.get("PE"), 33);
        grafo.agregarArista(n.get("PE"), n.get("OD"), 33);
        grafo.agregarArista(n.get("OD"), n.get("PC"), 33);
        grafo.agregarArista(n.get("PC"), n.get("OD"), 33);
        grafo.agregarArista(n.get("OE"), n.get("PE"), 10);
        grafo.agregarArista(n.get("PE"), n.get("OE"), 30);
        grafo.agregarArista(n.get("OE"), n.get("PF"), 33);
        grafo.agregarArista(n.get("PF"), n.get("OE"), 33);
        grafo.agregarArista(n.get("OG"), n.get("PG"), 10);
        grafo.agregarArista(n.get("PG"), n.get("OG"), 30);
        grafo.agregarArista(n.get("OG"), n.get("PH"), 33);
        grafo.agregarArista(n.get("PH"), n.get("OG"), 33);
        grafo.agregarArista(n.get("OG"), n.get("PF"), 33);
        grafo.agregarArista(n.get("PF"), n.get("OG"), 33);
        grafo.agregarArista(n.get("OI"), n.get("OJ"), 15);
        grafo.agregarArista(n.get("OJ"), n.get("OI"), 15);
        grafo.agregarArista(n.get("OI"), n.get("PJ"), 33);
        grafo.agregarArista(n.get("PJ"), n.get("OI"), 33);
        grafo.agregarArista(n.get("OI"), n.get("PH"), 33);
        grafo.agregarArista(n.get("PH"), n.get("OI"), 33);
        grafo.agregarArista(n.get("OJ"), n.get("PJ"), 10);
        grafo.agregarArista(n.get("PJ"), n.get("OJ"), 30);
        grafo.agregarArista(n.get("OJ"), n.get("PK"), 33);
        grafo.agregarArista(n.get("PK"), n.get("OJ"), 33);
        grafo.agregarArista(n.get("OL"), n.get("OM"), 15);
        grafo.agregarArista(n.get("OM"), n.get("OL"), 15);
        grafo.agregarArista(n.get("OL"), n.get("PM"), 33);
        grafo.agregarArista(n.get("PM"), n.get("OL"), 33);
        grafo.agregarArista(n.get("OL"), n.get("PK"), 33);
        grafo.agregarArista(n.get("PK"), n.get("OL"), 33);
        grafo.agregarArista(n.get("OM"), n.get("PM"), 10);
        grafo.agregarArista(n.get("PM"), n.get("OM"), 30);
        grafo.agregarArista(n.get("OM"), n.get("PN"), 33);
        grafo.agregarArista(n.get("PN"), n.get("OM"), 33);
        grafo.agregarArista(n.get("OO"), n.get("OP"), 15);
        grafo.agregarArista(n.get("OP"), n.get("OO"), 15);
        grafo.agregarArista(n.get("OO"), n.get("PP"), 33);
        grafo.agregarArista(n.get("PP"), n.get("OO"), 33);
        grafo.agregarArista(n.get("OO"), n.get("PN"), 33);
        grafo.agregarArista(n.get("PN"), n.get("OO"), 33);
        grafo.agregarArista(n.get("OP"), n.get("OQ"), 15);
        grafo.agregarArista(n.get("OQ"), n.get("OP"), 15);
        grafo.agregarArista(n.get("OP"), n.get("PP"), 10);
        grafo.agregarArista(n.get("PP"), n.get("OP"), 30);
        grafo.agregarArista(n.get("OP"), n.get("PQ"), 33);
        grafo.agregarArista(n.get("PQ"), n.get("OP"), 33);
        grafo.agregarArista(n.get("OQ"), n.get("OR"), 15);
        grafo.agregarArista(n.get("OR"), n.get("OQ"), 15);
        grafo.agregarArista(n.get("OQ"), n.get("PQ"), 10);
        grafo.agregarArista(n.get("PQ"), n.get("OQ"), 30);
        grafo.agregarArista(n.get("OQ"), n.get("PR"), 33);
        grafo.agregarArista(n.get("PR"), n.get("OQ"), 33);
        grafo.agregarArista(n.get("OQ"), n.get("PP"), 33);
        grafo.agregarArista(n.get("PP"), n.get("OQ"), 33);
        grafo.agregarArista(n.get("OR"), n.get("PR"), 10);
        grafo.agregarArista(n.get("PR"), n.get("OR"), 30);
        grafo.agregarArista(n.get("OR"), n.get("PQ"), 33);
        grafo.agregarArista(n.get("PQ"), n.get("OR"), 33);
        grafo.agregarArista(n.get("PA"), n.get("QB"), 33);
        grafo.agregarArista(n.get("QB"), n.get("PA"), 33);
        grafo.agregarArista(n.get("PC"), n.get("QC"), 10);
        grafo.agregarArista(n.get("QC"), n.get("PC"), 30);
        grafo.agregarArista(n.get("PC"), n.get("QD"), 33);
        grafo.agregarArista(n.get("QD"), n.get("PC"), 33);
        grafo.agregarArista(n.get("PC"), n.get("QB"), 33);
        grafo.agregarArista(n.get("QB"), n.get("PC"), 33);
        grafo.agregarArista(n.get("PE"), n.get("PF"), 15);
        grafo.agregarArista(n.get("PF"), n.get("PE"), 15);
        grafo.agregarArista(n.get("PE"), n.get("QF"), 33);
        grafo.agregarArista(n.get("QF"), n.get("PE"), 33);
        grafo.agregarArista(n.get("PE"), n.get("QD"), 33);
        grafo.agregarArista(n.get("QD"), n.get("PE"), 33);
        grafo.agregarArista(n.get("PF"), n.get("PG"), 15);
        grafo.agregarArista(n.get("PG"), n.get("PF"), 15);
        grafo.agregarArista(n.get("PF"), n.get("QF"), 10);
        grafo.agregarArista(n.get("QF"), n.get("PF"), 30);
        grafo.agregarArista(n.get("PF"), n.get("QG"), 33);
        grafo.agregarArista(n.get("QG"), n.get("PF"), 33);
        grafo.agregarArista(n.get("PG"), n.get("PH"), 15);
        grafo.agregarArista(n.get("PH"), n.get("PG"), 15);
        grafo.agregarArista(n.get("PG"), n.get("QG"), 10);
        grafo.agregarArista(n.get("QG"), n.get("PG"), 30);
        grafo.agregarArista(n.get("PG"), n.get("QH"), 33);
        grafo.agregarArista(n.get("QH"), n.get("PG"), 33);
        grafo.agregarArista(n.get("PG"), n.get("QF"), 33);
        grafo.agregarArista(n.get("QF"), n.get("PG"), 33);
        grafo.agregarArista(n.get("PH"), n.get("QH"), 10);
        grafo.agregarArista(n.get("QH"), n.get("PH"), 30);
        grafo.agregarArista(n.get("PH"), n.get("QI"), 33);
        grafo.agregarArista(n.get("QI"), n.get("PH"), 33);
        grafo.agregarArista(n.get("PH"), n.get("QG"), 33);
        grafo.agregarArista(n.get("QG"), n.get("PH"), 33);
        grafo.agregarArista(n.get("PJ"), n.get("PK"), 15);
        grafo.agregarArista(n.get("PK"), n.get("PJ"), 15);
        grafo.agregarArista(n.get("PJ"), n.get("QJ"), 10);
        grafo.agregarArista(n.get("QJ"), n.get("PJ"), 30);
        grafo.agregarArista(n.get("PJ"), n.get("QK"), 33);
        grafo.agregarArista(n.get("QK"), n.get("PJ"), 33);
        grafo.agregarArista(n.get("PJ"), n.get("QI"), 33);
        grafo.agregarArista(n.get("QI"), n.get("PJ"), 33);
        grafo.agregarArista(n.get("PK"), n.get("QK"), 10);
        grafo.agregarArista(n.get("QK"), n.get("PK"), 30);
        grafo.agregarArista(n.get("PK"), n.get("QL"), 33);
        grafo.agregarArista(n.get("QL"), n.get("PK"), 33);
        grafo.agregarArista(n.get("PK"), n.get("QJ"), 33);
        grafo.agregarArista(n.get("QJ"), n.get("PK"), 33);
        grafo.agregarArista(n.get("PM"), n.get("PN"), 15);
        grafo.agregarArista(n.get("PN"), n.get("PM"), 15);
        grafo.agregarArista(n.get("PM"), n.get("QM"), 10);
        grafo.agregarArista(n.get("QM"), n.get("PM"), 30);
        grafo.agregarArista(n.get("PM"), n.get("QN"), 33);
        grafo.agregarArista(n.get("QN"), n.get("PM"), 33);
        grafo.agregarArista(n.get("PM"), n.get("QL"), 33);
        grafo.agregarArista(n.get("QL"), n.get("PM"), 33);
        grafo.agregarArista(n.get("PN"), n.get("QN"), 10);
        grafo.agregarArista(n.get("QN"), n.get("PN"), 30);
        grafo.agregarArista(n.get("PN"), n.get("QO"), 33);
        grafo.agregarArista(n.get("QO"), n.get("PN"), 33);
        grafo.agregarArista(n.get("PN"), n.get("QM"), 33);
        grafo.agregarArista(n.get("QM"), n.get("PN"), 33);
        grafo.agregarArista(n.get("PP"), n.get("PQ"), 15);
        grafo.agregarArista(n.get("PQ"), n.get("PP"), 15);
        grafo.agregarArista(n.get("PP"), n.get("QP"), 10);
        grafo.agregarArista(n.get("QP"), n.get("PP"), 30);
        grafo.agregarArista(n.get("PP"), n.get("QQ"), 33);
        grafo.agregarArista(n.get("QQ"), n.get("PP"), 33);
        grafo.agregarArista(n.get("PP"), n.get("QO"), 33);
        grafo.agregarArista(n.get("QO"), n.get("PP"), 33);
        grafo.agregarArista(n.get("PQ"), n.get("PR"), 15);
        grafo.agregarArista(n.get("PR"), n.get("PQ"), 15);
        grafo.agregarArista(n.get("PQ"), n.get("QQ"), 10);
        grafo.agregarArista(n.get("QQ"), n.get("PQ"), 30);
        grafo.agregarArista(n.get("PQ"), n.get("QP"), 33);
        grafo.agregarArista(n.get("QP"), n.get("PQ"), 33);
        grafo.agregarArista(n.get("PR"), n.get("QQ"), 33);
        grafo.agregarArista(n.get("QQ"), n.get("PR"), 33);
        grafo.agregarArista(n.get("QB"), n.get("QC"), 15);
        grafo.agregarArista(n.get("QC"), n.get("QB"), 15);
        grafo.agregarArista(n.get("QB"), n.get("RB"), 10);
        grafo.agregarArista(n.get("RB"), n.get("QB"), 30);
        grafo.agregarArista(n.get("QB"), n.get("RA"), 33);
        grafo.agregarArista(n.get("RA"), n.get("QB"), 33);
        grafo.agregarArista(n.get("QC"), n.get("QD"), 15);
        grafo.agregarArista(n.get("QD"), n.get("QC"), 15);
        grafo.agregarArista(n.get("QC"), n.get("RB"), 33);
        grafo.agregarArista(n.get("RB"), n.get("QC"), 33);
        grafo.agregarArista(n.get("QF"), n.get("QG"), 15);
        grafo.agregarArista(n.get("QG"), n.get("QF"), 15);
        grafo.agregarArista(n.get("QF"), n.get("RF"), 10);
        grafo.agregarArista(n.get("RF"), n.get("QF"), 30);
        grafo.agregarArista(n.get("QF"), n.get("RG"), 33);
        grafo.agregarArista(n.get("RG"), n.get("QF"), 33);
        grafo.agregarArista(n.get("QG"), n.get("QH"), 15);
        grafo.agregarArista(n.get("QH"), n.get("QG"), 15);
        grafo.agregarArista(n.get("QG"), n.get("RG"), 10);
        grafo.agregarArista(n.get("RG"), n.get("QG"), 30);
        grafo.agregarArista(n.get("QG"), n.get("RH"), 33);
        grafo.agregarArista(n.get("RH"), n.get("QG"), 33);
        grafo.agregarArista(n.get("QG"), n.get("RF"), 33);
        grafo.agregarArista(n.get("RF"), n.get("QG"), 33);
        grafo.agregarArista(n.get("QH"), n.get("QI"), 15);
        grafo.agregarArista(n.get("QI"), n.get("QH"), 15);
        grafo.agregarArista(n.get("QH"), n.get("RH"), 10);
        grafo.agregarArista(n.get("RH"), n.get("QH"), 30);
        grafo.agregarArista(n.get("QH"), n.get("RI"), 33);
        grafo.agregarArista(n.get("RI"), n.get("QH"), 33);
        grafo.agregarArista(n.get("QH"), n.get("RG"), 33);
        grafo.agregarArista(n.get("RG"), n.get("QH"), 33);
        grafo.agregarArista(n.get("QI"), n.get("QJ"), 15);
        grafo.agregarArista(n.get("QJ"), n.get("QI"), 15);
        grafo.agregarArista(n.get("QI"), n.get("RI"), 10);
        grafo.agregarArista(n.get("RI"), n.get("QI"), 30);
        grafo.agregarArista(n.get("QI"), n.get("RJ"), 33);
        grafo.agregarArista(n.get("RJ"), n.get("QI"), 33);
        grafo.agregarArista(n.get("QI"), n.get("RH"), 33);
        grafo.agregarArista(n.get("RH"), n.get("QI"), 33);
        grafo.agregarArista(n.get("QJ"), n.get("QK"), 15);
        grafo.agregarArista(n.get("QK"), n.get("QJ"), 15);
        grafo.agregarArista(n.get("QJ"), n.get("RJ"), 10);
        grafo.agregarArista(n.get("RJ"), n.get("QJ"), 30);
        grafo.agregarArista(n.get("QJ"), n.get("RI"), 33);
        grafo.agregarArista(n.get("RI"), n.get("QJ"), 33);
        grafo.agregarArista(n.get("QK"), n.get("QL"), 15);
        grafo.agregarArista(n.get("QL"), n.get("QK"), 15);
        grafo.agregarArista(n.get("QK"), n.get("RJ"), 33);
        grafo.agregarArista(n.get("RJ"), n.get("QK"), 33);
        grafo.agregarArista(n.get("QL"), n.get("QM"), 15);
        grafo.agregarArista(n.get("QM"), n.get("QL"), 15);
        grafo.agregarArista(n.get("QL"), n.get("RM"), 33);
        grafo.agregarArista(n.get("RM"), n.get("QL"), 33);
        grafo.agregarArista(n.get("QM"), n.get("QN"), 15);
        grafo.agregarArista(n.get("QN"), n.get("QM"), 15);
        grafo.agregarArista(n.get("QM"), n.get("RM"), 10);
        grafo.agregarArista(n.get("RM"), n.get("QM"), 30);
        grafo.agregarArista(n.get("QM"), n.get("RN"), 33);
        grafo.agregarArista(n.get("RN"), n.get("QM"), 33);
        grafo.agregarArista(n.get("QN"), n.get("QO"), 15);
        grafo.agregarArista(n.get("QO"), n.get("QN"), 15);
        grafo.agregarArista(n.get("QN"), n.get("RN"), 10);
        grafo.agregarArista(n.get("RN"), n.get("QN"), 30);
        grafo.agregarArista(n.get("QN"), n.get("RM"), 33);
        grafo.agregarArista(n.get("RM"), n.get("QN"), 33);
        grafo.agregarArista(n.get("QO"), n.get("QP"), 15);
        grafo.agregarArista(n.get("QP"), n.get("QO"), 15);
        grafo.agregarArista(n.get("QO"), n.get("RN"), 33);
        grafo.agregarArista(n.get("RN"), n.get("QO"), 33);
        grafo.agregarArista(n.get("QP"), n.get("QQ"), 15);
        grafo.agregarArista(n.get("QQ"), n.get("QP"), 15);
        grafo.agregarArista(n.get("QP"), n.get("RQ"), 33);
        grafo.agregarArista(n.get("RQ"), n.get("QP"), 33);
        grafo.agregarArista(n.get("QQ"), n.get("RQ"), 10);
        grafo.agregarArista(n.get("RQ"), n.get("QQ"), 30);
        grafo.agregarArista(n.get("QQ"), n.get("RR"), 33);
        grafo.agregarArista(n.get("RR"), n.get("QQ"), 33);
        grafo.agregarArista(n.get("RA"), n.get("RB"), 15);
        grafo.agregarArista(n.get("RB"), n.get("RA"), 15);
        grafo.agregarArista(n.get("RE"), n.get("RF"), 15);
        grafo.agregarArista(n.get("RF"), n.get("RE"), 15);
        grafo.agregarArista(n.get("RE"), n.get("QD"), 33);
        grafo.agregarArista(n.get("QD"), n.get("RE"), 33);
        grafo.agregarArista(n.get("RE"), n.get("QF"), 33);
        grafo.agregarArista(n.get("QF"), n.get("RE"), 33);
        grafo.agregarArista(n.get("RF"), n.get("RG"), 15);
        grafo.agregarArista(n.get("RG"), n.get("RF"), 15);
        grafo.agregarArista(n.get("RG"), n.get("RH"), 15);
        grafo.agregarArista(n.get("RH"), n.get("RG"), 15);
        grafo.agregarArista(n.get("RH"), n.get("RI"), 15);
        grafo.agregarArista(n.get("RI"), n.get("RH"), 15);
        grafo.agregarArista(n.get("RI"), n.get("RJ"), 15);
        grafo.agregarArista(n.get("RJ"), n.get("RI"), 15);
        grafo.agregarArista(n.get("RL"), n.get("QK"), 33);
        grafo.agregarArista(n.get("QK"), n.get("RL"), 33);
        grafo.agregarArista(n.get("RL"), n.get("QL"), 10);
        grafo.agregarArista(n.get("QL"), n.get("RL"), 30);
        grafo.agregarArista(n.get("RL"), n.get("QM"), 33);
        grafo.agregarArista(n.get("QM"), n.get("RL"), 33);
        grafo.agregarArista(n.get("RL"), n.get("RM"), 15);
        grafo.agregarArista(n.get("RM"), n.get("RL"), 15);
        grafo.agregarArista(n.get("RM"), n.get("RN"), 15);
        grafo.agregarArista(n.get("RN"), n.get("RM"), 15);
        grafo.agregarArista(n.get("RP"), n.get("QO"), 33);
        grafo.agregarArista(n.get("QO"), n.get("RP"), 33);
        grafo.agregarArista(n.get("RP"), n.get("QP"), 10);
        grafo.agregarArista(n.get("QP"), n.get("RP"), 30);
        grafo.agregarArista(n.get("RP"), n.get("RQ"), 15);
        grafo.agregarArista(n.get("RQ"), n.get("RP"), 15);
        grafo.agregarArista(n.get("RQ"), n.get("RR"), 15);
        grafo.agregarArista(n.get("RR"), n.get("RQ"), 15);
 
        double escalaX = 1.6, escalaY = 1.8;
        for (Nodo nodo : grafo.getNodos()) {
            nodo.setX((int)(nodo.getX() * escalaX));
            nodo.setY((int)(nodo.getY() * escalaY));
        }
        return grafo;
    }
}